### ISSUE TITLE
File Naming Standard

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-diversity-inclusion#101]
I notice that we are naming files one of two ways:

with-dashes.md
with_underscores.md

I would like to propose the standard be for dashes.   If there is agreement, then the task is to update all files with underscores to dashes.

Thanks

**Comment by emmairwin** [comment]
Once we agree, this would be an easy first task for a new contributor.

**Comment by GeorgLink** [comment]
+1 for consistency
+1 for same standard use of dashes as wg-gmd
+1 good first issue

**Comment by UTpH** [comment]
Hi!
I was wondering if I can work on this issue?

**Comment by geekygirldawn** [comment]
@UTpH Yes! We'd love to have your help converting filenames with underscores to dashes! You'll need to a bit of searching through some of the READMEs to make sure that we update any links to these files as well. We'd also be happy to have you participate in other areas of the project :) We meet via a Zoom call every [Monday at 7:30am Pacific / 15:30 GMT](https://chaoss.community/participate/) if you want to join a meeting!

**Comment by UTpH** [comment]
Couple of doubts:-
1. Would you like to change folder names as well? For eg. focus_areas
2. Should the following be changed as well?
\wg-diversity-inclusion\examples\openstack\OpenStack Diversity Metrics 2017-S1.ipynb

**Comment by UTpH** [comment]
Baring the above, I have run a tiny script to rename the files and am waiting to submit a PR.

**Comment by GeorgLink** [comment]
> Would you like to change folder names as well? For eg. focus_areas

Yes, I think we should change folder names.

> What would these be ideally changed to?
>  \wg-diversity-inclusion\examples\openstack\OpenStack Diversity Metrics 2017-S1.ipynb

I vote for converting spaces to dashes.

>  \wg-diversity-inclusion\focus_areas\communication\communication_inclusivity-alternatives.md

I vote for converting all underscores to dashes.

**Comment by UTpH** [comment]
@GeorgLink 
Thanks for the clarifications!
