### ISSUE TITLE
Develop Resource Page: Communication Inclusivity: Alternatives

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#109]
This issue is for coordinating around developing the resource page for **Communication Inclusivity: Alternatives**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1e0Y0BhKqEeZeMpcttdFH8Q9NOq-Q6zp78aW-_65hMpc/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by sgoggins** [comment]
@GeorgLink I *think* we have addressed communication exclusivity in the metrics spreadsheet.

**Comment by GeorgLink** [comment]
Yes. I don't remember if there was anything else. Let's close this issue.
