### ISSUE TITLE
Develop Resource Page: Communication Inclusivity: Technical Jargon

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#110]
Develop Resource Page: Communication Inclusivity: Technical Jargon

This issue is for coordinating around developing the resource page for **Communication Inclusivity: Technical Jargon**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1t2P67jUWcoWUvhz1M2pfA6q7Pe16OWGyJNsTOBSDjcg/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
