### ISSUE TITLE
Develop Resource Page: Communication Inclusivity: Listening

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#114]
This issue is for coordinating around developing the resource page for **Communication Inclusivity: Listening**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1YHs1r-NHRTv1XoOcC-EnGDoo5tmYl-0WzfGuYmFbpEs/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by emmairwin** [comment]
This is an excellent resource to help with this 

https://docs.openstack.org/doc-contrib-guide/non-native-english-speakers.html#reading

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
