### ISSUE TITLE
Develop Resource Page: Contributions: Contribution Sentiment

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#118]
This issue is for coordinating around developing the resource page for **Contributions: Contribution Sentiment**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1oLr2kWKKbR8Vx7NrZ2xHXZ12cYN0vaqp1zehmF0IcKc/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by danwoqen** [comment]
Hi all - I've just had a listen to the March 4th D&I youtube recording and have a few questions on this before I suggest some edits;

- Is there a proposed mechanism / tool that will be used to measure sentiment across working groups? 
- Is the focus purely on measuring contribution sentiment? Can this be expanded to include additional areas? For example, when a new project kicks off ask contributors for their sentiments on diversity and inclusion initiatives (examining polarity, emotions & intentions)? The data produced should allow you to identify inclusive collaboration throughout the project lifecycle. However, you would need to have the capability of collecting responses as the project passes through different phases. The data could then be cut by gender / ethnicity (but this depends on how much diversity data you can figure out about each contributor).

**Comment by GeorgLink** [comment]
Welcome @danwoqen 

> Is there a proposed mechanism / tool that will be used to measure sentiment across working groups?

No. CHAOSS defines implementation-agnostic metrics. This means that any suitable tool could be used. It would be great to demonstrate that a metric can be implemented and this can be done in any tool.

> Scope

We are open to any of these options. To get the ball rolling, we like to start small and grow from there. We have low-hanging fruits and you are welcome to pick the ones most appealing to you.

Please let us know any additional questions or how we can help you make a contribution.

**Comment by sgoggins** [comment]
Are these in a focus area? @GeorgLink

**Comment by GeorgLink** [comment]
The focus area was renamed, not the folder that holds it. 
The metric needs to be defined more and then moved over to the repo.

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
