### ISSUE TITLE
Develop Resource Page: Leadership: Mentorship

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#120]
This issue is for coordinating around developing the resource page for **Leadership: Mentorship**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1pQnnbkDrVbZK_sJ8Nl84ijwxfHSmUNMwIDe5dVJ2pf4/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by SarahKConway** [comment]
@GeorgLink 
I've heard that mentorship programs are very western concept and not easily understood and commonly used in some geos. do we want to make this an objective. expand geo. reach of mentor programs where appropriate. Or document mentor best practices, how to instructions to encourage broader adoption? Or is it just not culturally accepted and we should be okay with mentor programs that have limited geo. reach.

**Comment by SarahKConway** [comment]
adding @uoduckswtd

**Comment by SarahKConway** [comment]
I added some comments to the objectives - some additional objectives to consider adding.

**Comment by GeorgLink** [comment]
Thanks @SarahKConway I have added a few more items and proposed a first set of sample metrics.

I'm going to surface Mentorship metric on the mailing list and put it on the agenda for next week.

**Comment by GeorgLink** [comment]
> I've heard that mentorship programs are very western concept and not easily understood and commonly used in some geos. do we want to make this an objective. expand geo. reach of mentor programs where appropriate. Or document mentor best practices, how to instructions to encourage broader adoption? Or is it just not culturally accepted and we should be okay with mentor programs that have limited geo. reach.

The goal of CHAOSS is to develop metrics to understand how we are doing. If mentorship is only interesting to some projects, that's okay. I don't think it is our goal to expand the use of mentorship. However, if our metrics demonstrate the value of mentorship to a project, then hopefully more projects choose to focus on mentorship.
