### ISSUE TITLE
Document WG Goals Proposal for 2019

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-diversity-inclusion#123]
Proposal Objectives and Key Results for WG in 2019

Some Questions to Answer
*  is the problem this working group is trying to solve?
* Why does it matter?
* Why does it matter to CHAOSS, and is there clear alignment?
* What then, is the objective CHAOSS D&I working group ties their goals and work towards in 2019?
* What are the Key Metrics for that objective ?

**Comment by emmairwin** [comment]
First draft for discussion in Monday call 

https://docs.google.com/document/d/1_rwp6f0teAyXZFkJien7nsmV2FankZDhLk9UmrT48vw/edit#

**Comment by emmairwin** [comment]
Initial draft  (without Key Results yet)

https://docs.google.com/document/d/1_rwp6f0teAyXZFkJien7nsmV2FankZDhLk9UmrT48vw/edit#heading=h.afrr9xwu1zby

**Comment by GeorgLink** [comment]
Thanks for putting this together @emmairwin I added comments in preparation for our call tomorrow.

**Comment by GeorgLink** [comment]
@emmairwin I tried to help by brainstorming key results for each objective. You may discard or change them freely - I am not married to any of these ideas.

**Comment by SarahKConway** [comment]
I made a few suggestions to the proposal, including another project to consider. I work on marketing at the Linux Foundation and am helping with our organization's D&I activities and involvement.

**Comment by GeorgLink** [comment]
@emmairwin can you please give us edit permission on the document?

**Comment by emmairwin** [comment]
done

**Comment by GeorgLink** [comment]
Thanks @emmairwin !

**Comment by GeorgLink** [comment]
We adopted the goals. Thanks again @emmairwin for advancing this issue and helping us move forward.
