### ISSUE TITLE
Recognize Non-Technical (and non-repo) contribution

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-diversity-inclusion#126]
Living by our metrics, I realize that 'who' has contributed to this project, beyond pull requests and comments is not clear.  And it should be.

I would like to see Nicole, and other core contributors (past and present) listed more centrally.
and also a way we track all contributions (like comments in our docs). Thoughts?

**Comment by emmairwin** [comment]
I would suggest because we are small right now, core contributors are people who are regular participants (once a month or more). 

And that we just become more diligent about keeping a list of name who show up, contribute but are not actively participating.

And build fromthere.

**Comment by GeorgLink** [comment]
+1

**Comment by geekygirldawn** [comment]
I like the idea of keeping a list of core contributors, and people who participate at least once a month sounds about right.

How about this as criteria for being added to the "core contributors": Participate at least once per month over a period of 3 months. Participation could include providing feedback in the weekly D&I meetings, providing feedback on docs, or making other contributions on GitHub (commits / issues). People not participating over a 3 month period may be removed as core contributors.

How about if we create a section in the README called "Contributors", move the current Maintainers section to "Contributors", and add "Core Contributors" along with the criteria to that section?

This would give more visibility to those contributions and show that we value them.

Assuming Georg & I are added to the MAINTAINERS section, I think we should add the following people to the Core contributors list:

* Matt Germonprez
* Nicole Huesman

Who am I missing?

**Comment by germonprez** [comment]
I went back through the D&I weekly meetings (just looking at the screen captures) and I think this is good. It does make me think that I need to do a better job of encouraging people to participate in the work groups.

**Comment by geekygirldawn** [comment]
I've submitted a pull request to add the contributors section to the readme: https://github.com/chaoss/wg-diversity-inclusion/pull/128

**Comment by GeorgLink** [comment]
Thanks @germonprez and @geekygirldawn. I added to #128 a list of 'all contributors' (to the best of my recollection, based on past emails, and based on past commit contributions).

**Comment by GeorgLink** [comment]
We merged the pull request #128. 
The readme now has our current definitions.

Is there any more need for discussion? 
Are there other things we can do to highlight (track) contributions?

**Comment by GeorgLink** [comment]
I think we resolved this issue.
