### ISSUE TITLE
Standardize README format between working groups.

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-diversity-inclusion#127]
Use [Richard Litt's Best Practices for README](https://github.com/RichardLitt/standard-readme), and make sure we have some similarity between the 2 WGs.

cc: @BenLloydPearson

**Comment by BenLloydPearson** [comment]
Thanks @geekygirldawn 

# Readme.md Structure
* Intro - Needs a one-line description, one paragraph description, and a short section that links to GMD metrics repo and explains how this repo fits into overall CHAOSS metrics effort.
* Table of Contents - Clickable links at the top are a lifesaver :-)
* Background - Should mostly stay the same, the Roadmap/current work content will be moved to another section
* Usage - Should contain the repository structure information with additional detail about the concepts behind focus areas and all other important elements of the repo with appropriate links.
* Roadmap - This section could use some improvement in clarity and detail. 
* Contribute - All of the content that references participation will be moved here and standardized with GMD repo
* License - A simple statement of the license that will be standardized with GMD repo

# Repository Structure

Additionally, I think it would be good to examine how the content of the directories is presented:

* templates, focus_areas, examples, ethics - These all need a Readme.md that describes the content of the directory with appropriate links
* demographic-data - I'm not sure I understand the purporse of this directory. The content appears to be valuable, but it's not clear how it fits within the big picture.


# Steps to Resolve

I think the best approach would be to create one PR for the README changes, followed by a series of PR's for each of the repositories. If we have consensus on the Readme.md changes I can get started on them. I'll do my best to retain all of the information you have, and I'll just present it under this new structure. With that said, there are likely some things I'll need help on with the details so I'll make sure we're on the same page with them.

**Comment by GeorgLink** [comment]
Discussion is happening in this google doc: 
https://docs.google.com/document/d/1pVtYHNTwrGFV3UyiR2qBKV0MvipoEEI-fbwavSNui4Q/edit

**Comment by jgbarah** [comment]
Just for you to know: once you're done with this discussion, we would try to merge in the GMD README as much as possible the diff with your result. Thanks for your work!

**Comment by GeorgLink** [comment]
We finalized the structure that would work for us today. Nicole is going to contact Ben about it.

**Comment by geekygirldawn** [comment]
I'm pretty sure that we did this a while ago and forgot to close the issue?

**Comment by GeorgLink** [comment]
+1 yes, I think you're right.

**Comment by geekygirldawn** [comment]
I'll close it now before we forget again :)
