### ISSUE TITLE
Idea: How to present our metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#129]
I just came across the [Open Design Kit](http://opendesignkit.org/) and found their presentation to resonate with how I imagine we could present our metrics and detail pages.

Specifically:
- Focus areas are at the top to allow filtering.
- Each metric gets a panel with a short description (question).
- When clicking a panel, the detail page opens.

This reduces the navigation within the metrics and creates a visually more appealing display than markdown pages. -- just a thought for publishing our metrics on our website later.

**Comment by sgoggins** [comment]
@GeorgLink : is this incorporated into discussions since December? Should this issue remain open?

**Comment by GeorgLink** [comment]
yes, we can close this
