### ISSUE TITLE
Develop Resource Page: Leadership: Sponsorship

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#135]
An interview partner pointed out that we currently do not have "Sponsorship" alongside mentorship but that it is an important and emerging metric. This issue is a proposal to add the metric.

This issue is for coordinating around developing the resource page for **Leadership: Sponsorship**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1J-9f_wYQxP26L_bF7JpS7Xez18cdM4WsKuw0UpBgVfU/

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by geekygirldawn** [comment]
This is great! I made a few comments and suggestions in the doc.

**Comment by GeorgLink** [comment]
Thank you @geekygirldawn for the edits and comments. I approved all of them and addressed your comment. Please review if the sentence makes sense now.

**Comment by geekygirldawn** [comment]
Looks great!

**Comment by SarahKConway** [comment]
I made a few additional suggestions and edits to the document! Really like this as an addition to the Leadership metric.

**Comment by GeorgLink** [comment]
Thank you @SarahKConway - You earned a 🥇 for advancing D&I metrics.

**Comment by GeorgLink** [comment]
We worked on the metric during today's weekly call. 

We need to work on the explanation of what sponsorship is and how it is different from mentorship.

**Comment by geekygirldawn** [comment]
This metric was released

**Comment by paras151** [comment]
What changes do we now need to make to the google document.I am kinda new here.

**Comment by GeorgLink** [comment]
Hi @paras151. Thanks for alerting me to this issue. We already resolved this and the issue should be closed.

Our process for defining a metric is to prototype it in a google doc, then move it to a markdown page in the repository. Finally, the metric is released, like the Sponsorship metric of this issue was released: https://chaoss.community/metric-sponsorship/

**Comment by geekygirldawn** [comment]
@paras151 If you are interested in helping to develop some other metrics, we are always looking for help! The best way to start is by joining one of our meetings - details here: https://chaoss.community/participate/ If you can't make the meetings, reach out to us on the mailing list, and we can help find something interesting for you to work on :)
