### ISSUE TITLE
License on repository not complient with CHAOSS charter

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#149]
The CHAOSS charter states in section 8.2.3:
> All contributions to implementation-agnostic metrics and standards, including associated scripts, SQL statements, and documentation, will be received and made available under the MIT License.

I never noticed it, but our workgroup repository has a GPL-3.0 license.

This issue is to discuss whether we can change the license in the repository, since it should have been MIT from the beginning but people contributed, maybe thinking it was GPL-3.0.

**Comment by geekygirldawn** [comment]
Because decisions about relicensing are pretty complex and might have legal ramifications for The Linux Foundation, we definitely need to get LF legal counsel involved in making this decision. Maybe @kestewart can help pull someone to represent the LF from a legal perspective into this thread?

**Comment by geekygirldawn** [comment]
I've also removed the good first issue label, since this decision has potential legal ramifications stretching beyond CHAOSS and into the LF as our parent org.

**Comment by BenLloydPearson** [comment]
To take this a bit further, MIT and GPL are both designed to be used on code, which this repo has very little of. Instead, my interpretation is that most of this repo would be considered content, which is best provided under a Creative Commons license. Realistically, this repo should probably be dual licensed, 1)MIT for any code examples, and 2) CC for the rest of the content.

With that said, we absolutely need to work with the LF on this, and we will probably need to get permission from all contributors to change the license on this repo.

**Comment by GeorgLink** [comment]
> With that said, we absolutely need to work with the LF on this, and we will probably need to get permission from all contributors to change the license on this repo.

+1 fully agree. 

Let me provide some history below.

We worked with Mike Dolan from the LF when we established CHAOSS. We wrote section 8.2.3 of the charter to state:
> All contributions to implementation-agnostic metrics and standards, including associated scripts, SQL statements, and documentation, will be received and made available under the MIT License

We discussed Creative Commons but decided against. If I remember correctly, this was because MIT is liberal enough to also apply to documentation and what we expected to be our metric definitions, along side code samples.

**Comment by GeorgLink** [comment]
I hope we can discuss this at the GB meeting at the Leadership Summit.

**Comment by jgbarah** [comment]
I agree with @BenLloydPearson on his proposal of licenses for code (reference implementations) and text (description of metrics, etc.).

Instead of just moving this to the GB, I would suggest preparing a proposal (what @BenLloydPearson proposes could be most of it) for the GB, and if needed discuss with other wgs (GMD, at least is also affected), so that it can be discussed knowing the opinion of the wgs (I think there will be consensus here, anyway).

**Comment by GeorgLink** [comment]
Good idea

**Comment by germonprez** [comment]
Agreed. Good idea. I would like the separation myself (code and text). I'll put this on the board agenda.
