### ISSUE TITLE
The Responsible Communication Style Guide

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#150]
I just discovered The Responsible Communication Style Guide. 
Has anyone read it? - I didn't buy it (yet).
Is this a good resource for any of our metrics?

https://rcstyleguide.com/

**Comment by SarahKConway** [comment]
I have not heard of this. Do you know any of the backers? I just emailed to ask if the style guide is updated on a regular basis or if an updated edition is planned. I believe it came out in 2017. I am thinking of buying it regardless.

**Comment by GeorgLink** [comment]
I do not know any backer. The Responsible Communication Style Guide was mentioned by someone who I interviewed for our metrics.

**Comment by emmairwin** [comment]
I am only aware of this because we worked with  Audrey Eschright on the Code of Conduct review tool, and she is an author. Looks like a great resource.

**Comment by geekygirldawn** [comment]
@GeorgLink Can we close this one? It looks pretty old.

**Comment by GeorgLink** [comment]
yes.
