### ISSUE TITLE
A safe, sustainable, and secure way to handle data without compromising user privacy. 

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#152]
I just had a phone call about collecting D&I metrics with privacy in mind and I was pointed to this place for work on collecting metrics that protect privacy: https://github.com/cleaninsights/

> A safe, sustainable, and secure way to handle data without compromising user privacy. 

The project looks stale (last commit in 2017) and because it comes out of a university there might be no future development on this. However, maybe there may be some ideas we could use in this document: https://github.com/cleaninsights/cleaninsights-android-sdk

**Comment by sgoggins** [comment]
@GeorgLink : What do you think about closing this issue?

**Comment by GeorgLink** [comment]
we can close it. if we need this info again, we can find :D
