### ISSUE TITLE
Communication Inclusivity: Technical Jargon Question

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#162]
As I'm aligning the D&I work with the metrics repo, the question associated with this metric is not clear.

**Comment by emmairwin** [comment]
Sorry Matt, I think I see where you are going with these issues, would you mind linking the resource you are referring to, for quicker lookup?  Thank you

**Comment by germonprez** [comment]
Hi @emmairwin. This is like _Alternatives_ in the Communication focus area. Just a note to finalize the question.

**Comment by geekygirldawn** [comment]
For clarity, I'm assuming this issue refers to [communication-inclusivity-technical-jargon.md](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/communication/communication-inclusivity-technical-jargon.md)

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
