### ISSUE TITLE
Focus Area Questions

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#164]
Hi all, 

As I continue to move through the focus areas to align them with the Metrics repo, I'm noticing that the questions in the Focus Area tables don't always line up with the detail pages.

**Comment by emmairwin** [comment]
Hi Matt, can you provide an example of a page that doesn't line up?, and we can turn this into a good first issue.

**Comment by germonprez** [comment]
Sure. Code of Conduct doesn't line up: 

https://github.com/chaoss/wg-diversity-inclusion/tree/master/focus-areas/governance

**Comment by sgoggins** [comment]
PR Merged.
