### ISSUE TITLE
Contribution Type

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#165]
There are two Contribution Type metrics in the D&I focus areas: 

https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/recognition/contribution-type.md

and 

https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/contribution/contribution-type.md

**Comment by GeorgLink** [comment]
Thanks @germonprez 

Closing because it's duplicate of #122
