### ISSUE TITLE
Intern project ideas

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#166]
Last week we had decided to draft a project ideas for a potential Outreachy or other intern.
The description may be helpful in finding contributors.

## Project Description for CHAOSS D&I Outreachy Intern 

An Outreachy intern would directly contribute to the goals of the CHAOSS D&I Working Group. The D&I Working Group develops ethical, peer-validated, research-informed sets of standards and best practices for measuring diversity and inclusion in open source projects. An Outreachy intern has several ways to participate with the CHAOSS D&I Working Group, depending on their interests and skills. Interns may use the following project ideas to propose a project they are most interested in.

### Project Idea 1
An intern can learn how to prepare D&I metrics and consult with open source projects that want to prepare and deploy metrics within their own communities. An intern can collect feedback and lessons learned and update the CHAOSS D&I Working Group documentation. The intern can write blog posts about how projects deployed and used D&I metrics to share best practices. This work requires customer service orientation and excellent communication. 

### Project Idea 2
An intern interested in technical aspects of metrics can implement D&I metrics in software. This addresses the issue that many D&I metrics are currently labor intensive because they rely on manual data collection and analysis. The developed software can be piloted with open source projects and experience reports can be published via blog posts. This work requires developing software and analyzing data.

### Project Idea 3
An intern interested in documentation and data visualization can revise D&I metric definitions. D&I metric definitions contain descriptions of data collection methods and display options. The intern would make definitions easier to use and include example displays for D&I metrics. This work requires working with open source projects to collect feedback on definitions and data visualizations.

**Comment by GeorgLink** [comment]
During D&I call 2019-02-25, we decided that we will not pursue additional interns, because RedHat and Boston University are starting a project that includes three part-time students who will be working on D&I metrics. We want to see how much mentoring the RedHat/BU project requires, before adding more interns and over-extending our mentor capacity.

I am undecided whether to leave this issue open. The project ideas may be valuable in the future. However, when we are ready to look for an intern, ideas may be different and have to be updated anyways. 

Thoughts?

**Comment by emmairwin** [comment]
I realize this is not exactly the purpose of this thread, but if I had an intern work on this stuff, it would be to spend time going through  all metrics and collecting and citing research to validate what we have in the first version.

**Comment by GeorgLink** [comment]
> I realize this is not exactly the purpose of this thread, but if I had an intern work on this stuff, it would be to spend time going through all metrics and collecting and citing research to validate what we have in the first version.

That is another great project idea!

**Comment by emmairwin** [comment]
@GeorgLink shall we close this now?   Or do you want to retain it as a wiki page?

**Comment by GeorgLink** [comment]
Yes 👍
