### ISSUE TITLE
require DCO for all new commits

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#170]
This issue is to activate [protobot/dco](https://github.com/apps/dco) (or similar bot) to check that all commits have a sign-off. The CHAOSS Project Charter requires that all contributions are signed-off. 

For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`

For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**Comment by GeorgLink** [comment]
I piloted the DCO bot with the chaoss/governance repo. 
The largest hurdle is that we all will have to remember to sign-off on our commits.
I automate this in browser when using the GitHub UI with above mentioned browser plugin.
Locally, if one forgets, `git commit amend -s` adds the sign-off later.

Once we have sufficiently communicated that this change coming, we can activate the DCO bot.

**Comment by GeorgLink** [comment]
We should updated our CONTRIBUTE.md before activating the DCO bot.

I can create a pull request, similar to the one on the chaoss/governance repo:
https://github.com/chaoss/governance/pull/100/files

**Comment by Polaris000** [comment]
This is a great idea!. Though I am a regular user of gpg keys with the command line, I never signed my commits when directly working with github, since github autosigns commits. 
Will love to try the sign-off feature on github though.

**Comment by GeorgLink** [comment]
> The link to scottrigby/dco-gh-ui leads to the github landing page. Please have a look

@Polaris000 could you figure out how to use the browser plugin?

**Comment by GeorgLink** [comment]
DCO bot is now active.

During yesterday's call, we agreed to activate the DCO bot and everyone was given advance notice through previous meetings and meeting minutes.

**Comment by Polaris000** [comment]
> @Polaris000 could you figure out how to use the browser plugin?
Of course!

**Comment by GeorgLink** [comment]
Perfect 👍

**Comment by Polaris000** [comment]
Where should I mention the steps to use the plugin?

**Comment by GeorgLink** [comment]
🥇 
The CONTRIBUTING.md would be a good place for this

**Comment by Polaris000** [comment]
Thanks for the prompt reply!. Will send a pull request. Should I send a pull request to each repository?

**Comment by GeorgLink** [comment]
It would be great to update all repositories.
I suggest starting with one.
