### ISSUE TITLE
"Level of Completeness" exercise

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#174]
In preparation of releasing metrics, the working group needs to decide by end of June which metrics to include in the release. This gives us time to further develop metrics and prepare them for the release.

To develop a plan of action, we need to understand where we stand today. To help with determining the level of completeness, please: 

1. Open shared google doc: https://docs.google.com/spreadsheets/d/1_jwkwzs8s6SAm2vVY-8lzTQk3YT0YpOveTlKOwjd2eQ/edit?usp=sharing
1. add your name to a column below
1. lookup metrics at https://github.com/chaoss/wg-diversity-inclusion
1. for each metric, give your vote on whether the metric is good or needs before the release; or whether it should not be part of the release.

On April 15, during the D&I WG meeting, we will discuss the votes and discuss an action plan.

**Comment by GeorgLink** [comment]
We did the exercise during the call on 2019-04-15.

2) The output of this exercise is a classification for each metric:

    green (g) - good for release
    yellow (y) - needs some work, but include in release
    blue (b) - missing or needs major work, but goal is to have it ready for release
    red (r) - ignore for this release

With the goal to have at least one metric in each focus area, we have the following metrics ear marked for release:

1. Event Diversity   
    (y) Speaker Demographics
    (y) Attendees Demographics
    (g) Diversity Access Tickets
    (g) Code of Conduct at Event
    (g) Family Friendliness
2. Contributor Community Diversity   
    (b) Demographic diversity
3. Communication Inclusivity   
    (b) Listening
    (b) Speaking
4. Recognition of Good Work   
    (b) Contribution Type
5. Leadership   
    (g) Mentorship
    (y) Sponsorship (issue #135)
6. Governance   
    (y) Foundation Staff Diversity
    (y) Board/Council Diversity
    (y) Code of Conduct
    (y) Code of Conduct Enforcement
    (y) Team/Module Ownership Diversity
7. Project and Community   
    (y) Documentation

**Comment by sgoggins** [comment]
@GeorgLink : Do we know the status of this issue? It looks like it may be closable.

**Comment by GeorgLink** [comment]
this was done in preparation for the first release. we can close the issue
