### ISSUE TITLE
Candidate Release Comments (Diversity Access Tickets)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#183]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Diversity Access Tickets**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/events/diversity-tickets.md

Release candidate: https://chaoss.community/metric-diversity-access-tickets/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
LGTM
