### ISSUE TITLE
Candidate Release Comments (Code of Conduct at Event)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#184]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Code of Conduct at Event**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/events/event-code-of-conduct.md

Release candidate: https://chaoss.community/metric-code-of-conduct-at-event/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
Likert scale [1-4] item: How well did the event meet your code of conduct expectations.

This should end with a question mark
