### ISSUE TITLE
Candidate Release Comments (Family Friendliness)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#185]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Family Friendliness**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/events/family-friendly.md

Release candidate: https://chaoss.community/metric-family-friendliness/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
Likert scale [1-4] item: How family friendly is the event?

Set your scale to 1-5 to allow for neutral options.

**Comment by geekygirldawn** [comment]
There are a lot of opinions about whether likely scales should be odd or even depending on the situation. I think we should take a neutral stance and say [1-x]. Thoughts?

**Comment by geekygirldawn** [comment]
I’m also good with Matt’s suggestion, too :)

**Comment by germonprez** [comment]
1-x is a good idea. 

(This suggestion would apply to all other D&I metrics where this issue comes up).

**Comment by GeorgLink** [comment]
1-x is fine with me. I had originally included 1-x because I don't expect everyone to know what "likert scale" means.

**Comment by klumb** [comment]
Remove text from resources section
