### ISSUE TITLE
Candidate Release Comments (Code of Conduct)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#188]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Code of Conduct**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/governance/code-of-conduct.md

Release candidate: https://chaoss.community/metric-code-of-conduct

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by foundjem** [comment]
Communities might be encouraged to have an ombudsperson, and to ensure the rights, confidentiality and dignity of violated persons. Also, to make sure every community member knows their **rights** and **responsibilities**.

**Comment by mpgjon** [comment]
I'd like to recommend that on the Inclusivity front, there be a set of suggested statements/actions that projects can and should state to speak to inclusivity. 

For example:
Does the Code of Conduct (or some other file in a Governance repo) define the actions the project community commit to with regards to:

- Availability/commitment to of accessible meetings either via captioning or real-time note taking for hearing impaired?
- Availability/commitment to making project related materials available color-blind or large-text readable formats for vision impaired?

**Comment by germonprez** [comment]
Should this be called **Code of Conduct for Project** to help delineate it from CoC for Event.

**Comment by germonprez** [comment]
Like other metrics, set the Likert scale to 1-5

**Comment by GeorgLink** [comment]
@mpgjon's comment is intriguing. I think this inclusivity aspect is part of other metrics. 

https://github.com/chaoss/wg-diversity-inclusion/tree/master/focus-areas/communication

**Comment by GeorgLink** [comment]
> Communities might be encouraged to have an ombudsperson, and to ensure the rights, confidentiality and dignity of violated persons. Also, to make sure every community member knows their **rights** and **responsibilities**.

We added a question to reflect the rights and responsibility aspect.
