### ISSUE TITLE
Ensure CHAOSS front-end components are color-blind accessible

### ISSUE THREAD

**Issue by mpgjon** [chaoss/wg-diversity-inclusion#197]
To ensure CHAOSS is inclusive and accessible, dashboard layouts, and front end components should be reviewed for compliance with color-blindness development standards. 

There's a good test filter service here that can be used to test pages: https://www.toptal.com/designers/colorfilter 

Acceptance Criteria should include:
Given that a component of CHAOSS has a front end page
When that page is reviewed using a color-blindness filter
Then that page is still readable for color-blind users

For pages that need changes in order to be accessible, separate issues should be opened:)

**Comment by germonprez** [comment]
Ah! Does this link help answer my question in #198?

**Comment by germonprez** [comment]
@klumb is there anything we can do to help in this regard via wordpress? I'm not sure how much control we have.

**Comment by klumb** [comment]
Thanks @mpgjon, we are always interested in making the website more inclusive. 

I have reviewed the home page using the tool that you provided and believe that it gets a passing grade. I welcome outside reviews and am happy to make changes.

Should a page be found that isn't in compliance, an issue can be opened on the website repo. We can fix these issues independently. 

The color palette and template for the website were selected by the Linux Foundation folks so large changes would likely have to go through them. However, I believe the website is using a color-blind safe palette though so wholesale changes may not be an issue.

**Comment by klumb** [comment]
Please see website issue chaoss/website#408

Asking for volunteers to conduct inclusivity reviews
