### ISSUE TITLE
[Mentorship] Discussion on the addition of extra metrics to the mentor/mentee context

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-diversity-inclusion#201]
I'm opening a new ticket with a comment from @foundjem at #186 .

As that ticket was focused on the process to freeze metrics for the release candidate, it was needed to move out that discussion of the ticket, sorry @foundjem for this ;).

The following is part of the discussion for mentorship. Thanks!

> Interesting!
> 
> Moreover, Mentorship if conducted properly could help educate mentees about the work culture of a project/community. Also, well-formed mentees can contribute quality code, which represent best practices because they have learned these skills over the Mentorship period.
> 
> Have some few questions though, how long will the mentorship program last?
> Can a mentee change their mentor after the mentorship have started?
> Can a mentee be allowed to participate in more than one mentorship program in a row?

**Comment by sgoggins** [comment]
@foundjem and @dicortazar : What is the status?

**Comment by germonprez** [comment]
@foundjem and @dicortazar I'm not sure where this is at. Is this related to current metrics releases: 

https://chaoss.community/metric-mentorship/

Or is this about mentorship within the CHAOSS project?

**Comment by germonprez** [comment]
Hello all :) @foundjem and @dicortazar do either of you have an update on this issue?

**Comment by conferencepapers** [comment]
Hello @germonprez, I guess there was a metric around this topic, which could apply to any context on mentoring.
Hopefully, it can go in the metric review/release. 

Sign-off-by: Armstrong <foundjem@ieee.org>

**Comment by germonprez** [comment]
There is this metric that has been released: 
https://chaoss.community/metric-mentorship/

I will consider this release as addressing this issue.
