### ISSUE TITLE
Code of Conduct (Project)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#212]
@GeorgLink @klumb This change did not seem to make it through. Could you double check? 

Also, a few changes need to follow: 

- Name of the metric to reflect the inclusion of 'project'
- Website table to reflect the name change.

**Comment by klumb** [comment]
@germonprez, I don't see a PR for this change? 

Are we changing the name of the md file as well?

**Comment by germonprez** [comment]
I could have sworn I saw it go across the screen :)

**Comment by GeorgLink** [comment]
I'll check

**Comment by GeorgLink** [comment]
I created a new PR: https://github.com/chaoss/wg-diversity-inclusion/pull/213

**Comment by klumb** [comment]
Website table is updated. I don't think we need to change the name of md file.
