### ISSUE TITLE
Question for Event Diversity users "diverse people"

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#216]
Gil Yehuda commented while working on [TODO's diversity guide](https://docs.google.com/document/d/1x3irlDLuM2GZ4AvvcAVoave_NoA0HLWv8u5OlHPpZTk/edit?ts=5d50448f) on the question we have for Event Diversity:

> I have a concern with the phrase "diverse people" since diversity is a feature of a collection. A person can't be diverse. I hear people use the phrase to mean "someone who can help improve my D&I numbers" and I cringe that were tokenizing people for their contributions to the numbers, and not actually valuing them for their unique person-ness.

I think that Gil is making a good point and I propose we revise the question.

**Comment by sgoggins** [comment]
@GeorgLink : What is the status?

**Comment by GeorgLink** [comment]
No work has been done to resolve this issue

**Comment by germonprez** [comment]
@GeorgLink I think this has been resolved as I do not see the term 'diverse people' in our metrics.

**Comment by GeorgLink** [comment]
Thanks for checking :)
