### ISSUE TITLE
Revise Order of Focus Areas

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#217]
I think at one point, our Focus Areas were alphabetized... then we revised them. Now, the order is not obvious and I don't know for sure why we have the focus areas in our current order.

Gil Yehuda commented:
> Observation: I think the thing that makes open source D&I so hard is that the vast majority of open source projects don't have events. Only the big name ones with corporate sponsors or those that are lucky enough to have a meetup. So almost all the time the issues we face are not event-issues (which are better addressed with event Code of Conduct and have unique issues like face to face interactions, etc.). So I find is odd that this is the first thing listed.

I propose that we reconsider the order of our focus areas and maybe revise it.

**Comment by sgoggins** [comment]
@klumb and @germonprez ; Is this something you would do in the ordinary progress of standardizing metrics definitions.

**Comment by klumb** [comment]
@GeorgLink, this appears to be a comment on the metrics release. Is that correct?

The order of the focus areas on the website was dictated by the spreadsheet we were using to coordinate the release.

I don't think we discussed order prior to release for V1 but alphabetical would make sense.  

I think this is an issue we resolve in the next release. However, if we want to fix this now it is easy.

**Comment by GeorgLink** [comment]
No need to change released metrics. 

I agree, this issue can be solved with a PR to make order alphabetical in the README and the focus-areas/README
