### ISSUE TITLE
Retaining woman in open source: Organising open source day montly

### ISSUE THREAD

**Issue by tapaswenipathak** [chaoss/wg-diversity-inclusion#219]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting. I will share further information.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by GeorgLink** [comment]
Hi @tapaswenipathak.

It is great that you found the CHAOSS Diversity and Inclusion Working Group (D&I WG). We care deeply about the issue you point out.

The CHAOSS D&I WG is familiar with the research you mention and several members are actively involved in initiatives that improve their communities' diversity and inclusivity. The CHAOSS D&I WG has an approach of providing metrics for communities to assess how well they are doing with regards to diversity and inclusion, thus giving hints at how to improve. I hope that explains a little about what this group is about. 

I am curious how you think we can help and what additional information you have.
We can discuss here on the issue, or on our [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/chaoss-diversity-inclusion), or on our weekly call, which is open to anyone to join.

The D&I working group meets every Monday at 9:30am CT (usually 16:30 CET, [check your local time](http://arewemeetingyet.com/Chicago/2018-11-05/09:30/w/CHAOSS%20D%26I%20WG)) via [Zoom](https://unomaha.zoom.us/j/720431288) -- [Agenda and Meeting Minutes](https://docs.google.com/document/d/1MzDk84BL7FfHDxbFxJz39M72V2Hfc5Y6oCPhOl6woxo/edit)

**Comment by tapaswenipathak** [comment]
Hello,

I mail the proposal out.

On Sat, Aug 24, 2019 at 6:55 PM Georg J.P. Link
<notifications@github.com> wrote:
>
> Hi @tapaswenipathak.
>
> It is great that you found the CHAOSS Diversity and Inclusion Working Group (D&I WG). We care deeply about the issue you point out.
>
> The CHAOSS D&I WG is familiar with the research you mention and several members are actively involved in initiatives that improve their communities' diversity and inclusivity. The CHAOSS D&I WG has an approach of providing metrics for communities to assess how well they are doing with regards to diversity and inclusion, thus giving hints at how to improve. I hope that explains a little about what this group is about.
>
> I am curious how you think we can help and what additional information you have.
> We can discuss here on the issue, or on our mailing list, or on our weekly call, which is open to anyone to join.
>
> The D&I working group meets every Monday at 9:30am CT (usually 16:30 CET, check your local time) via Zoom -- Agenda and Meeting Minutes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Thanks,
Tapasweni

**Comment by tapaswenipathak** [comment]
Hello,

Thanks! I will mail the proposal out.

On Sat, Aug 24, 2019 at 6:55 PM Georg J.P. Link
<notifications@github.com> wrote:
>
> Hi @tapaswenipathak.
>
> It is great that you found the CHAOSS Diversity and Inclusion Working Group (D&I WG). We care deeply about the issue you point out.
>
> The CHAOSS D&I WG is familiar with the research you mention and several members are actively involved in initiatives that improve their communities' diversity and inclusivity. The CHAOSS D&I WG has an approach of providing metrics for communities to assess how well they are doing with regards to diversity and inclusion, thus giving hints at how to improve. I hope that explains a little about what this group is about.
>
> I am curious how you think we can help and what additional information you have.
> We can discuss here on the issue, or on our mailing list, or on our weekly call, which is open to anyone to join.
>
> The D&I working group meets every Monday at 9:30am CT (usually 16:30 CET, check your local time) via Zoom -- Agenda and Meeting Minutes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Thanks,
Tapasweni
