### ISSUE TITLE
Collect existing D&I surveys

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#220]
The idea is to collect existing D&I surveys to have references for what questions have been used and to have an overview of what has been done and reported.

The collection should contain:
1. Survey questionnaires
2. Survey results and reports

We can collect the information in a public google doc:
https://docs.google.com/document/d/1GsGdfr4eqbh_bWTH5oYbQcko6OGAlmQCo8-BqybEFoo/edit#

I'll reach out to other groups as well.

**Comment by ivamarr** [comment]
Hi @GeorgLink, 

I would love to contribute to this project as we are doing an Open Source for Good project at the office. Are you still looking for data on this issue? Thanks!

**Comment by GeorgLink** [comment]
Yes, we are still interested in additional surveys.

On Monday 10/7  during our weekly meeting, we have on the agenda to go
thorough the current connection. I invite you to join us then.

Georg

**Comment by GeorgLink** [comment]
I'm closing the issue because I got the sense that we got everything important collected.
Markdown export from the google doc (just in case it goes away)


# Collection of Surveys on D&I in open source

**Call to action:** Please add below references you know of related to surveys that were done in recent years to understand diversity and inclusion in open source communities. 


Hi,

The CHAOSS D&I Working Group decided to collect a list of past D&I surveys in open source: [https://github.com/chaoss/wg-diversity-inclusion/issues/220](https://github.com/chaoss/wg-diversity-inclusion/issues/220)

The collection of D&I surveys should contain:

1. Survey questionnaires

2. Survey results and reports

Collecting past surveys is the first step for identifying reusable survey questions as well as getting a baseline for comparison. It would be great to pool our resources across the open source ecosystem. 

The CHAOSS D&I Working Group has also been working on new survey questions that may be added to future D&I surveys. Therefore, we propose to collect all kinds of questions within the CHAOSS D&I Working Group and make them available to anyone who wants to run a D&I survey in the future.

The CHAOSS D&I Working Group needs your help to identify what D&I surveys have been done in the past and collecting the survey questions that have been used.

**Please add below links to resources, surveys, and reports of surveys.**

Thank you!

---

# Contribute Here

Please paste in here links to surveys, resources, and reports about surveys that have been done on the diversity and inclusion in open source. The CHAOSS D&I Working Group will organize all submissions later.

Optional Submission template:

*   &lt;Name of Survey, or organization that ran the survey>
    *   &lt;Year, if known>
    *   &lt;Link to survey questions, if known>
    *   &lt;Link to survey data, results, or report, if known>
    *   &lt;Additional comments>

---

*   Apache 
    *   Year: 2016 [https://cwiki.apache.org/confluence/display/COMDEV/ASF+Committer+Diversity+Survey+-+2016](https://cwiki.apache.org/confluence/display/COMDEV/ASF+Committer+Diversity+Survey+-+2016)
        *   Feedback: [https://lists.apache.org/thread.html/e94038f420a5151c2a0e4874313afd88a7d08e1f56c29d39fb4076ae@%3Cdev.community.apache.org%3E](https://lists.apache.org/thread.html/e94038f420a5151c2a0e4874313afd88a7d08e1f56c29d39fb4076ae@%3Cdev.community.apache.org%3E)
    *   Plans to run a new survey: [https://issues.apache.org/jira/projects/DI/issues/DI-27?filter=allopenissues](https://issues.apache.org/jira/projects/DI/issues/DI-27?filter=allopenissues)

*   Mozilla
    *   Year: 2017 (?)
    *   Presentation with results: [https://docs.google.com/presentation/d/13UxBGj2lI66SLjl6sp4NE3DH2ndT0k5QM0pPyyzZXuY/edit](https://docs.google.com/presentation/d/13UxBGj2lI66SLjl6sp4NE3DH2ndT0k5QM0pPyyzZXuY/edit)
    *   Survey items: [https://github.com/mozilla/diversity/tree/master/data-metrics/surveys/en](https://github.com/mozilla/diversity/tree/master/data-metrics/surveys/en)

*   New Kernel Contributor Survey, Linux Foundation
    *   Year: Ongoing
    *   Responsible for survey: Shuah Khan
    *   Email template: [https://drive.google.com/file/d/1ih17JAQzwWDqr53FK698tCJYqIytg1q7/view](https://drive.google.com/file/d/1ih17JAQzwWDqr53FK698tCJYqIytg1q7/view)
    *   Live survey in Google Forms: [https://docs.google.com/forms/d/e/1FAIpQLSdFDwiE_D9MuYs2jpG7RnQ0J6YGQJMExiTKiKXOP1GWW7kEXg/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdFDwiE_D9MuYs2jpG7RnQ0J6YGQJMExiTKiKXOP1GWW7kEXg/viewform)

*   Open Demographics project
    *   Year: N/A
    *   Website: [http://nikkistevens.com/open-demographics/](http://nikkistevens.com/open-demographics/)
    *   Note: Collection of survey questions for obtaining demographic information from respondents.

*   Open Source Survey, GitHub
    *   Year: 2017
    *   Results: [https://opensourcesurvey.org/2017/](https://opensourcesurvey.org/2017/) 
    *   Survey questions: [https://github.com/github/open-source-survey/blob/master/survey-instrument.md](https://github.com/github/open-source-survey/blob/master/survey-instrument.md)
        *   Work related to the survey can be found in this public repo: [https://github.com/github/open-source-survey](https://github.com/github/open-source-survey)

*   OpenStack Diversity Survey
    *   2015 (original survey)
    *   Draft - [https://docs.google.com/forms/d/19P117V1OxZgRuPP6S2nwNCH6cC6v0jwwAaFswwLNqTc/edit](https://docs.google.com/forms/d/19P117V1OxZgRuPP6S2nwNCH6cC6v0jwwAaFswwLNqTc/edit)
    *   Board Presentation - [https://docs.google.com/presentation/d/1nMUYOLcjg3bPC-KueqRLrPpNKwG4BDY3ghKkqTUUgXk/edit?usp=sharing](https://docs.google.com/presentation/d/1nMUYOLcjg3bPC-KueqRLrPpNKwG4BDY3ghKkqTUUgXk/edit?usp=sharing)

*   OpenStack Diversity Survey
    *   2019
    *   Final Draft - [https://etherpad.openstack.org/p/diversity-survey-spring-2018_final](https://etherpad.openstack.org/p/diversity-survey-spring-2018_final)
    *   WG Presentation - [https://github.com/spotz/diversity/blob/master/2019DiversitySurveyResults.pdf](https://github.com/spotz/diversity/blob/master/2019DiversitySurveyResults.pdf)

*   Perception of Diversity on GitHub
    *   Survey items: [https://bvasiles.github.io/papers/diversity_survey.pdf](https://bvasiles.github.io/papers/diversity_survey.pdf)
    *   Report: [https://bvasiles.github.io/papers/chase15.pdf](https://bvasiles.github.io/papers/chase15.pdf)
    *   Related report: [https://cmustrudel.github.io/papers/chi15.pdf](https://cmustrudel.github.io/papers/chi15.pdf)

*   TODO Group Survey
    *   Year 2018 and 2019
    *   Link to questions and data: [https://github.com/todogroup/survey](https://github.com/todogroup/survey) 
    *   Note: Demographics are not typical D&I but employer profiles

*   International Institute of Infonomics, Free/Libre and Open Source Software: Survey and Study
    *   Year: 2002
    *   Report: [http://flossproject.merit.unu.edu/report/Final4.htm](http://flossproject.merit.unu.edu/report/Final4.htm)

*   Red Hat
    *   Fedora Project, Diversity and Inclusion Team
        *   2017-2018
        *   [https://docs.fedoraproject.org/en-US/diversity-inclusion/demographic-survey/#survey-questions](https://docs.fedoraproject.org/en-US/diversity-inclusion/demographic-survey/#survey-questions)
        *   _Survey never ran_
        *   **_NOTE_**: This survey never launched. The community drove a year of research and planning into a demographic survey, but the survey was stuck inside Red Hat Legal. To this day, the survey is blocked but all of our work and notes are in the Fedora Wiki.

*   StackOverflow, member survey
    *   Year: 2018
    *   Report: [https://insights.stackoverflow.com/survey/2018/](https://insights.stackoverflow.com/survey/2018/)
    *   Note: Interesting [Developer Role and Gender analysis](https://insights.stackoverflow.com/survey/2018/#developer-profile-_-developer-role-and-gender)

*   Wikimedia, Charting Diversity in Wikipedia
    *   Year: 2014
    *   Report: [https://upload.wikimedia.org/wikipedia/commons/5/57/Charting_Diversity.pdf](https://upload.wikimedia.org/wikipedia/commons/5/57/Charting_Diversity.pdf)

*   Women in Debian 2013
    *   Year: 2013
    *   Report, including method: [http://penta.debconf.org/dc13_schedule/attachments/243_women_in_debian_2013.pdf](http://penta.debconf.org/dc13_schedule/attachments/243_women_in_debian_2013.pdf)

*   OpenStack Gender Report
    *   2017: [https://superuser.openstack.org/wp-content/uploads/2017/07/OpenStack-Gender-Diversity-Report_Apr2017.pdf](https://superuser.openstack.org/wp-content/uploads/2017/07/OpenStack-Gender-Diversity-Report_Apr2017.pdf)
    *   2018: [https://superuser.openstack.org/wp-content/uploads/2018/06/Gender-Diversity-Analysis-in-the-OpenStack-Community-2018.pdf](https://superuser.openstack.org/wp-content/uploads/2018/06/Gender-Diversity-Analysis-in-the-OpenStack-Community-2018.pdf)

*   Public Lab
    *   Year: 2019
    *   [https://forms.gle/oCte2JYAcDWe2tx37](https://forms.gle/oCte2JYAcDWe2tx37) and draft w/ discussion: [https://publiclab.org/questions/warren/10-25-2017/help-with-a-standard-mini-evaluation-for-assessing-software-outreach-efforts](https://publiclab.org/questions/warren/10-25-2017/help-with-a-standard-mini-evaluation-for-assessing-software-outreach-efforts) 
    *   [https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey](https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey) 

*   Gnome Foundation
    *   [https://wiki.gnome.org/InclusionAndDiversity](https://wiki.gnome.org/InclusionAndDiversity)
