### ISSUE TITLE
Travel funding / diversity access tickets

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-diversity-inclusion#222]
After talking to Angela, we should probably include something about travel funding to go along with the [diversity access tickets](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/events/diversity-tickets.md). The LF have found that without the travel funding, most people can't afford to attend even with a free ticket.

**Comment by germonprez** [comment]
I've label this issue as Metric Idea and am closing the issue. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
