### ISSUE TITLE
Code of Conduct at Event Page - add a template

### ISSUE THREAD

**Issue by ivamarr** [chaoss/wg-diversity-inclusion#223]
In the Known Implementations Resources section at the bottom of https://chaoss.community/metric-code-of-conduct-at-event/ add an additional resource that helps Events add code of conducts. 

Montréal's Women in Tech developed a really helpful template to implement at events that could be a helpful in this page. 
https://manifestedesfemmesentech.com/en/code-of-conduct-template

**Comment by geekygirldawn** [comment]
Thanks!
