### ISSUE TITLE
Event Diversity - Family Friendliness - Add resources 

### ISSUE THREAD

**Issue by ivamarr** [chaoss/wg-diversity-inclusion#224]
On the page Event Diversity - Family Friendliness https://chaoss.community/metric-family-friendliness/
Add the following resources at the bottom section of Known Implementations
Resources: 
- https://adacamp.org/adacamp-toolkit/childcare/
- https://open.nytimes.com/what-if-child-care-were-as-standard-as-coffee-at-tech-conferences-568c5fba028e

**Comment by geekygirldawn** [comment]
Thanks so much!
