### ISSUE TITLE
Diversity Access Tickets - add resources

### ISSUE THREAD

**Issue by ivamarr** [chaoss/wg-diversity-inclusion#226]
Add resources at the bottom of the page in _Known Implementations
Resources_ section
- https://internetfreedomfestival.org/internet-freedom-festival-diversity-inclusion-fund/

**Comment by GeorgLink** [comment]
@ivamarr thank you for your suggestion. This has been added to our [Diversity Access Tickets](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/events/diversity-tickets.md) metric.
