### ISSUE TITLE
Release Candidate Comments (Board/Council Diversity)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#258]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Board/Council Diversity**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/governance/board-council-diversity.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Remove Focus Area prior to metric name -- this is consistent with the layout of the other release candidate metrics.

**Comment by GeorgLink** [comment]
I am marking this as ready to release and closing the issue. Please reopen if that is not the case.
