### ISSUE TITLE
Release Candidate Comments (Code of Conduct for Project)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#259]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Code of Conduct for Project**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/governance/code-of-conduct.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Resources needs to be References.

**Comment by GeorgLink** [comment]
I am marking this as ready to release and closing the issue. Please reopen if that is not the case.
