### ISSUE TITLE
Release Candidate Comments (Mentorship)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#260]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Mentorship**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/mentorship.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Do not _italics_ the References

**Comment by germonprez** [comment]
Remove redundant line: 
Survey Likert item (1-x): I would recommend mentoring for this community.

**Comment by GeorgLink** [comment]
I am marking this as ready to release and closing the issue. Please reopen if that is not the case.
