### ISSUE TITLE
Release Candidate Comments (Sponsorship)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#261]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Sponsorship**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/sponsorship.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Remove Focus Area prior to metric name -- this is consistent with the layout of the other release candidate metrics.

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
http://www.talentinnovation.org/publication.cfm?publication=1330 appears to be a pay only link

**Comment by germonprez** [comment]
Edit bullet points to get aligned.

**Comment by GeorgLink** [comment]
I am marking this as ready to release and closing the issue. Please reopen if that is not the case.
