### ISSUE TITLE
Release Notes (D&I)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#262]
Please leave comments and notes here to help construct the release notes document.

**Comment by germonprez** [comment]
New Metrics Include: 
- Sponsorship 
- Board/Council Diversity

**Comment by GeorgLink** [comment]
We improved clarity on several metrics. Maybe we want to include that, so people know the metrics changed a little.

**Comment by germonprez** [comment]
Thanks
