### ISSUE TITLE
Weekly Badge-athons (all welcome to join)

### ISSUE THREAD

**Issue by SMotaal** [chaoss/wg-diversity-inclusion#277]
We started a weekly weekend work session between @Nebrethar and @SMotaal taking place this and every other Sunday 11 am to 1 pm Eastern Time (see your [local time](https://www.wolframalpha.com/input/?i=Sunday+11+am+to+1+pm+Eastern+Time)).

This time block involves some discussions, and occasional moments of silence for individual work done sync.

All welcome to join of course via [zoom](https://zoom.us/j/885031449?pwd=ak1mdnY1cWNwbDBndFMzSy9oa1FFUT09)!

**Comment by GeorgLink** [comment]
Thanks for sharing the invite!

**Comment by SMotaal** [comment]
@GeorgLink would be great if we can add it to the shared calendar… and would be great if we can somehow be able to cancel or reschedule if necessary, however that could work best.

**Comment by GeorgLink** [comment]
@klumb maintains the calender.

**Comment by SMotaal** [comment]
@bistaastha would you be interested in joining us in those Bi-weekly meetings?

**Comment by SMotaal** [comment]
@Nebrethar I just asked that we move make D&I meeting updates on badging a bi-weekly agenda item to sync it with our pace.

We tentatively consider having it on next and every other week following that — ie March 11 is week 11 of 2020. This way we can hammer on fresh input from that meeting while it is relatively fresh, come up with async chores and use the board to report back. 

> **Note** — I will also personally block that Wednesday on my calendar as branding and badging office hours :)

This will be ideal if we put thought in how we keep our cards aligned with the overall process, ie either (or anyone else involved) of us can digest and update in our D&I bi-weekly meetings.

Sounds like a process?

**Comment by bistaastha** [comment]
> @bistaastha would you be interested in joining us in those bi-weekly meetings?

Sure!

**Comment by thecraftman** [comment]
Hi, i am ore-aruwaji tola i am interested in contributing to the CHAOSS outreachy project on - Build Workflow Process for CHAOSS Diversity & Inclusion Badging

**Comment by bistaastha** [comment]
Hi @SMotaal! As discussed during the last Badge-athon, one was scheduled for this Sunday as well. Will you be sending out an invite for that or is everything same as last time?

**Comment by Nebrethar** [comment]
Badgathons are moving to weekly. @SMotaal I nitpick for a name change on this page. 😄

**Comment by germonprez** [comment]
Closing
