### ISSUE TITLE
Discussion: Fine-graining the Documentation Accessibility description.

### ISSUE THREAD

**Issue by SMotaal** [chaoss/wg-diversity-inclusion#279]
This issue tracks discussions related to the Description section of the Documentation Accessibility draft.

<table><tr><tr><td>

## Description

Documentation accessibility contains issues of technical accessibility as well as readability issues with the goal to foster understanding <ins>for the widest audience of potential contributors to the project. Users of documentation have different abilities, ways of accessing or consuming documentation, requiring it to be offered in different formats that would be equally empowering these different users’ points of view</ins>. Accessibility of documentation is critical due to the role documentation plays in open source projects. Documentation is codified knowledge across various dimensions of an open source project.

Documentation on the processes and practices of the community empowers participants to contribute with certainty for how and why things are happening. It may also be on the artifacts produced by the community and as such empower participants to know where to contribute and what kind of contributions further the goals of the community.

</table>

---

<details>

---

<table><tr><td>

Documentation accessibility contains issues of technical accessibility as well as readability issues with the goal to foster understanding <ins>`for the widest audience of potential contributors to the project`</ins>¹<del title="without disproportionately contributing to or offsetting artificial debts on certain segments of its intended audience">`, without disproportionately contributing to or offsetting artificial debts on certain segments of its intended audience`</del>²<del title="without disproportionately creating or perpetuating artificial debts on certain segments of its intended audiences">`, without disproportionately creating or perpetuating artificial debts on certain segments of its intended audiences`</del>³<ins>`. Users of documentation have different abilities, ways of accessing or consuming documentation, requiring it to be offered in different formats that would be equally empowering these different users’ points of view`</ins>⁴. Accessibility of documentation is critical due to the role documentation plays in open source projects. Documentation is codified knowledge across various dimensions of an open source project.

</table>

1. <ins>`for the widest audience of potential contributors to the project`</ins>
   > **Note** — This is very common verbiage for most projects today.

2. <del title="without disproportionately contributing to or offsetting artificial debts on certain segments of its intended audience">`, without disproportionately contributing to or offsetting artificial debts on certain segments of its intended audience`</del>

   > @jlovejoy:
   >
   > I'd keep positive framing for this thing - it's more salient that way.

   > @SMotaal:
   >
   > Unfortunately my problem has been positive framing === systematic filtering, can we please find a way to not delete this.

   > @jlovejoy:
   >
   > I think my issue was with the use of "contributing" - it is correct, but I want to save it for "contributing to the project" type references!

3. <del title="without disproportionately creating or perpetuating artificial debts on certain segments of its intended audiences">`, without disproportionately creating or perpetuating artificial debts on certain segments of its intended audiences`</del>

   >  **Note** — This is the often glossed over reality that becomes immutable when someone tries to point out why documentation is actually "disabling" that way… most sadly resign to giving up, and we end up we folks thinking that they are accessible and it was just individual incompetence validated by opting for self-exclusion (ie retreat).

4. <ins>`. Users of documentation have different abilities, ways of accessing or consuming documentation, requiring it to be offered in different formats that would be equally empowering these different users’ points of view`</ins>

   >  @GeorgLink:
   >
   > this attempts to clarify that documentation needs to be tailored to the specific needs of different types of users.

</details>

---

[Google Document](https://docs.google.com/document/d/1OaKDksmuoi6nhaduZ4F96mTwQJvIFnfI8BqLx4MRO38/edit?pli=1#heading=h.c9v1ikdaw5rs)

**Comment by SMotaal** [comment]
## Comments

> @jlovejoy:
>
> I'd keep positive framing for this thing - it's more salient that way.

> @SMotaal:
>
> Unfortunately my problem has been positive framing === systematic filtering, can we please find a way to not delete this.
> 
> (I don't mind discussing background elsewhere to help find a more conventionally okay way, obviously I am not able to keep my emotions out of this, but we are creating and hiding artificial disability and opening issues only leads to further "why so serious" because the conventions are far more disabling when they are considered the working template to enhance around)

> @jlovejoy:
>
> you have something specific in mind, which I think I'm missing - yes, let's do discuss.
>
> in the meantime - let me see if I understand the intent of the language I crossed out: I think you are trying to stress that documentation should both:
>
> 1. try to be accessible, inclusive; but also
> 2. try to not to perpetuate some of the bias (not sure that's the right word) that currently exist.
>
> is that roughly right in simplistic terms?
>
> if so, it's like saying: you should try to do the right thing - but good intentions are not enough - you also need to be aware of the common pitfalls and work to avoid them
>
> otherwise, good intentions can lead to same not-so-good result

**Comment by SMotaal** [comment]
@jlovejoy, I do apologize, but the comments in the doc got too crowded… hope you don't mind discussing this here!

**Comment by jlovejoy** [comment]
I think we may have mostly resolved this in the doc??

**Comment by GeorgLink** [comment]
I believe we resolved it today.

**Comment by SMotaal** [comment]
> **Aside** — Can we leave at least 24 hours open in the future (re dwelling thoughts please).

---

So let's see a real-world example about accessibility, but please, do not just take a glance, this does not work if you do not try to operate with the urgency and sense of despair one might feel if they cannot play because they got the broken controller!

I've spent a very long time slowly figuring out how to GitHub is positioning its accessibility runaround… and decided they are publically disclosing their commitments and obligations so I decided based on our meeting yesterday to start another one of those inhumane and offensive efforts to try to remember that people are nice, even when the world is telling me but not to someone like me… https://github.com/SMotaal/a11y/issues/7
