### ISSUE TITLE
Discussion: Collaboration Accessibility

### ISSUE THREAD

**Issue by SMotaal** [chaoss/wg-diversity-inclusion#280]
Based on all the amazing efforts by everyone on the [Documentation Accessibility metric doc](https://docs.google.com/document/d/1OaKDksmuoi6nhaduZ4F96mTwQJvIFnfI8BqLx4MRO38/edit), I feel it is fair to start discussing the idea of a "Collaboration Accessibility" metric.

This issue would hopefully lead to a more concrete proposal for the metric, which I certainly have only my frame of reference to motivate me to work towards it.

The title chosen just follows the current structure, but it obviously does not roll off the tongue as easy as say "Accessibility in Collaboration".

The idea is to extrapolate from what we've considered around the single-user experience for documentation and consider them from a multi-user experience (ie bridging across different frames of reference) — I like to say UX versus CX (that is not yet a thing as far as I know).

There is a lot to it that comes in projects choosing (or advocating for) tools that are accessible, so this kind of [runaround](https://github.com/SMotaal/a11y/issues/7) that is kept out of public channels does not end up being the presumed burden of those are sadly told by projects (and I quote) "we're not equipped" or "you do your thing"!

**Comment by GeorgLink** [comment]
Thank you for this suggestion.
