### ISSUE TITLE
Discuss recommendation for Open Demographics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#286]
@emmairwin and I had a conversation on the D&I in OSS mailing list about survey questions for demographics.

The CHAOSS D&I WG has been recommending the Open Demographics questions so that we don't duplicate work. 
The Open Demographics project has not been actively maintained for a while now. 

Emma and I see two paths forward:
1. Fork Open Demographics and maintain it within CHAOSS
2. Recommend the [survey questions maintained by Mozilla](https://github.com/mozilla/diversity/blob/master/data-metrics/surveys/en/disability.md)

**Comment by ElizabethN** [comment]
> Recommend the survey questions maintained by Mozilla

Just to clarify, this would include all the survey questions, not just the ones around dis/ability, correct?

**Comment by GeorgLink** [comment]
Yes, all questions for demographics :)

**Comment by germonprez** [comment]
I'm going to open an issue in the Open Demographics repo to address this issue.

**Comment by germonprez** [comment]
This has been resolved. Matt G. and Georg L. are now maintainers on the Open Demographics repo. We had a great discussion regarding the relationship between the two projects.
