### ISSUE TITLE
Release Candidate Comments (Documentation Usability)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#288]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Documentation Usability**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/README.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202008/

**Comment by klumb** [comment]
Link to metric:
https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/documentation-usability.md

**Comment by foundjem** [comment]
LGTM! 

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by mbbroberg** [comment]
This is a collection of great practices and advice. I'm curious if there's advice that could be offered to roll the experience into a metric from the qualitative approach listed. For example: "After interviewing, the community can track responses to each prompt as `Positive experience`, `Negative experience, or `Neutral experience` and report these month-over-month to see improvement over time." 

What do you think @GeorgLink?

**Comment by mbbroberg** [comment]
One more thing: the phrase "structured intuitively" has some unspoken assumption to it that I'm not sure what is intended. I _think_ it is: "structured intuitively based on common practices as outlined [here]" where [here] is the benchmark or standard we're basing this concept off.

**Comment by mariamgui** [comment]
This is a great metric idea, the fact that it involves the input of actual newcomers in the data collection is really interesting and would provide a good perspective 👍 

Some minor suggestions about the example interview questions: 

Since the first two questions are open ended we can switch the phrasing to  _"**describe** your experience with using the documentation to understand the contribution process?"_  that would emphasize more on the open ended character of the question and help get more detailed answers. 

Third example question could be phrased: "_**How** comfortable are you with the amount of technical terms present here?"_ and we can present it as a likert scale question that way we get a bit more nuanced answers than a yes/ no.

**Comment by GeorgLink** [comment]
> Third example question could be phrased: "How comfortable are you with the amount of technical terms present here?" and we can present it as a likert scale question that way we get a bit more nuanced answers than a yes/ no.

We accepted this suggestion. Thank you!

**Comment by GeorgLink** [comment]
> Since the first two questions are open ended we can switch the phrasing to "describe your experience with using the documentation to understand the contribution process?" that would emphasize more on the open ended character of the question and help get more detailed answers.

Thank you, we like this suggestion and accept it.

**Comment by GeorgLink** [comment]
> One more thing: the phrase "structured intuitively" has some unspoken assumption to it that I'm not sure what is intended. I think it is: "structured intuitively based on common practices as outlined [here]" where [here] is the benchmark or standard we're basing this concept off.

Thank you @mbbroberg , we remove "structured intuitively" and replaced it with "understanding"

**Comment by dabbish** [comment]
Great idea to get at the issue of documentation usability. Regarding comfort with language / technical terms - what about asking:

"Were there any terms or language you didn't understand?"

To help identify specific instances of confusing terminology to iterate on or add definitions for.

**Comment by GeorgLink** [comment]
@mbbroberg 

> This is a collection of great practices and advice. I'm curious if there's advice that could be offered to roll the experience into a metric from the qualitative approach listed. For example: "After interviewing, the community can track responses to each prompt as Positive experience, Negative experience, or Neutral experience and report these month-over-month to see improvement over time."
>
> What do you think @GeorgLink?

I opened #301 to see if that works for you

**Comment by mbbroberg** [comment]
Absolutely @GeorgLink, that'd work from my perspective.

**Comment by rpaik** [comment]
Under data collection strategies one of the bullets says "Describe your experience with using the documentation to understand the contribution process." 

I don't think it should be limited to the contribution process as they will be people (e.g. users) who will be reading documentations to understand the software, technology, etc.

**Comment by rpaik** [comment]
Would a possible metrics for documentation usability be the number of documentation bugs/issues?

**Comment by germonprez** [comment]
Hi @rpaik 

The "Describe your experience with using the documentation to understand the contribution process." is just an example. It could certainly include other forms of engagement. What do you think about adding another bullet point like: 

"Describe your experience with using the documentation to understand how to help outreach efforts."

For the bugs/issues comment, do you think that would be its own top-level bullet point under Data Collection Strategies?

**Comment by klumb** [comment]
@GeorgLink is this metric ready?

**Comment by germonprez** [comment]
Ready for release
