### ISSUE TITLE
Release Candidate Comments (Inclusive Leadership)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#292]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Inclusive Leadership**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/inclusive-leadership.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202008/

**Comment by foundjem** [comment]
Overall, I think this metric is of utmost importance. However, I have one concern, on the "inclusive leadership cycle," six structured principles serve as a check-list. Are those related to the six listings below? Moreover, I don't know if there are sequential steps. For example, you must start from step 1, then step 2, etc., (clockwise) I think it's important to know the flow of things.

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by GeorgLink** [comment]
Thank you @foundjem for the feedback :)

We removed the confusing figure and removed the numbering to avoid implying sequential order.

**Comment by mbbroberg** [comment]
Awesome addition to our community! I offer a minor edit in #298. Great work gang :smile:

**Comment by rpaik** [comment]
Under Objectives, it should perhaps read "Signal to newcomers that everyone is welcome and everyone can be successful"

The way it's written now, it sounds like only certain people will be welcome.

**Comment by rpaik** [comment]
One item that seems to be missing is where these guidelines should be documented. Ax example list maybe helpful (e.g. Code of Conduct, Participation Guidelines, Bylaws, or other governance documents).

**Comment by germonprez** [comment]
Thanks @rpaik -- I issued a PR for the objectives statement. Do you have thoughts on where your guidelines documentation comment could live in the metric?

**Comment by klumb** [comment]
@GeorgLink is this metric ready?

**Comment by germonprez** [comment]
Ready for release.
