### ISSUE TITLE
Duplicate Metrics

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/wg-diversity-inclusion#305]
At the release, we will have some duplicate metrics. For example...

[Issue Tracker](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/issue-tracker.md) and [Issue Label Inclusivity](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/issue-label-inclusivity.md)
[Documentation](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/documentation.md) and [Documentation Usability](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/documentation-usability.md)

Let me know if you find more!

**Comment by GeorgLink** [comment]
Decided today in meeting: 

remove https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/issue-tracker.md
* We have a specific implementation with Issue Label Inclusivity

remove https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/documentation.md
  * This is now three new metrics Documentation {Accessibility, Usability, Discoverability}

**Comment by Nebrethar** [comment]
Thanks!

**Comment by germonprez** [comment]
This issue has been addressed through the following PRs

#340 
#341 
#342
