### ISSUE TITLE
Release Notes - 2021-02

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-diversity-inclusion#311]
This issue was created to capture the continuous contribution notes. Insight from comments will be used to create the regular release notes.

Example comments could be:

name of new metric and date of release
descriptions of changes to existing metric
Changes to focus areas or restructuring of WG

**Comment by GeorgLink** [comment]
New metric: Project Burnout (#316)

New metric: Documentation Accessibility (#320)

**Comment by klumb** [comment]
New metric: Chat Platform Inclusivity #328

**Comment by klumb** [comment]
Closing for release
