### ISSUE TITLE
Release Candidate Comments (Project Burnout)

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/wg-diversity-inclusion#319]
This issue was created to collect comments about the next metrics release.

This thread is for comments about the Project Burnout metric.

Release candidate at: https://chaoss.community/metric-project-burnout/
GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/project-burnout.md

**Comment by LawrenceHecht** [comment]
Was there already a discussion about including this metric in one of the other working groups? For example, burnout is obviously a risk factor.

**Comment by LawrenceHecht** [comment]
Are you looking for an alerting system for individual contributors or for the overall community? 

Many of the suggested survey questions won't work -- how do you do an anonymous survey when there are only a small group of contributors?

**Comment by GeorgLink** [comment]
Thanks @LawrenceHecht 

> Was there already a discussion about including this metric in one of the other working groups? For example, burnout is obviously a risk factor.

Yes, the burnout metric and others can be used for different purposes. We currently place metrics with the working group that defined the metric. We have had conversations about how to better present the metrics that reflects their different use cases.

> Are you looking for an alerting system for individual contributors or for the overall community?

My understanding of the metric is that it is for the overall community.

> Many of the suggested survey questions won't work -- how do you do an anonymous survey when there are only a small group of contributors?

We have not tested the survey questions or seen anyone implement them. Do you have suggestions for improving the metric description?

**Comment by LawrenceHecht** [comment]
> We have not tested the survey questions or seen anyone implement them. Do you have suggestions for improving the metric description?

@GeorgLink I will try to attend the Wednesday working group meeting and provide feedback then. If I don't attend, I'll provide more feedback directly in this issue thread.

**Comment by GeorgLink** [comment]
We discussed on the D&I WG call today that keeping the metric in one (not split) would be better for conveying the importance of this metric. We acknowledge that there is a lot going on in the metric but we see it as a feature to inspire people and when someone wants to implement it we can have a new conversation about how to use it in a specific context. 

We continue to accept comments and suggested changes.

**Comment by sgoggins** [comment]
Status quo.

**Comment by LawrenceHecht** [comment]
Making a note here that I have a PR related to this metric: https://github.com/chaoss/wg-diversity-inclusion/pull/343

**Comment by klumb** [comment]
Closing for release

Unmerged PRs #343  and #347 - Please address in the next release
