### ISSUE TITLE
Release Candidate Comments (Chat Platform Inclusivity) 

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#328]
This issue was created to collect comments about the next metrics release.

This thread is for comments about the Chat Platform Inclusivity metric.

Release candidate at: https://chaoss.community/chat-platform-inclusivity/
GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/chat-platform-inclusivity.md

**Comment by Sing-Li** [comment]
Hello,  the metrics seem to assume that the open source organization owns one instance of the chat platform.   Some platform allows mapping of a code repository per chat room (or per set of chat rooms), with multiple organizations/projects sharing an instance.   Perhaps the metrics should take this into account.

**Comment by germonprez** [comment]
Hi @Sing-Li and thanks for the thoughtful comment. Do you have thoughts on where/how this might be best captured in the current metric?

**Comment by Sing-Li** [comment]
Hmm.  Perceval already collects data per channel, so there is no need to modify the data collection strategies.       (thanks for the reply @germonprez !)

But I do see interchangeable mixed use of “Chat Platform” and “Chat Service” in the current doc.

Perhaps standardizing the use of the term “Chat Platform” within the document, and add an explicit explanation in the “Description” clarifying that a “Chat Platform” may include “public shared Chat service” where an open source project may occupy a set of channels.

**Comment by germonprez** [comment]
Great advice! I'll take a pass at the doc and maybe tag you for a look in the PR :)

**Comment by germonprez** [comment]
Hi @Sing-Li I've created PR #345 to address these concerns. Do you think this works?

**Comment by jwflory** [comment]
#345 is now merged. 🎉

**Comment by rpaik** [comment]
I see IRC listed as an example platform that both requires and doesn't require persistent connections and this is obviously confusing. Are there actually platforms that require persistent connections?

**Comment by rpaik** [comment]
Also, maybe we remove "Platforms" from 

- Number of active Chat Platforms / rooms / groups

This may give people the impression that we're advocating for multiple chat platforms (e.g. Slack, IRC, RocketChat, etc.) in a community.

**Comment by jwflory** [comment]
> **@rpaik wrote…**
> I see IRC listed as an example platform that both requires and doesn't require persistent connections and this is obviously confusing. Are there actually platforms that require persistent connections?

@rpaik I am curious to better understand your thoughts here. I am not following your confusion. Is there an inclusivity issue you think this metric should look at with persistent or non-persistent connections? I could follow this train of thought, but I am wondering if this is something to detail in the metric.

> **@rpaik wrote…**
> Also, maybe we remove "Platforms" from
> 
>     * Number of active Chat Platforms / rooms / groups
> 
> This may give people the impression that we're advocating for multiple chat platforms (e.g. Slack, IRC, RocketChat, etc.) in a community.

+1. PRs for this are welcome. 🙂

**Comment by Nebrethar** [comment]
> Release candidate at: https://chaoss.community/chat-platform-inclusivity/

Currently a 404. Pinging @klumb for roadside service on this issue!

**Comment by rpaik** [comment]
> > **@rpaik wrote…**
> > I see IRC listed as an example platform that both requires and doesn't require persistent connections and this is obviously confusing. Are there actually platforms that require persistent connections?
> 
> @rpaik I am curious to better understand your thoughts here. I am not following your confusion. Is there an inclusivity issue you think this metric should look at with persistent or non-persistent connections? I could follow this train of thought, but I am wondering if this is something to detail in the metric.
My question is are you saying IRC requires a persistent connection or it doesn't? I don't think it could be both.
> 
> > **@rpaik wrote…**
> > Also, maybe we remove "Platforms" from
> > ```
> > * Number of active Chat Platforms / rooms / groups
> > ```
> > 
> > 
> > This may give people the impression that we're advocating for multiple chat platforms (e.g. Slack, IRC, RocketChat, etc.) in a community.
> 
> +1. PRs for this are welcome. 🙂

**Comment by klumb** [comment]
Closing for release
