### ISSUE TITLE
Discussion on the addition of "bugs suited for novices" in the Project Places Goal

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-diversity-inclusion#33]
At the PR https://github.com/chaoss/wg-diversity-inclusion/pull/24, there was an ongoing discussion about having specific bugs suited for novices.

Comment by @aserebrenik on the PR by @emmairwin  "Some projects explicitly tag bugs suited for novices to facilitate the onboarding process. This is related to the discussion about the README in the Project places file."

The referenced Goal can be found at https://github.com/chaoss/wg-diversity-inclusion/blob/master/goal_project_places.md

**Comment by GeorgLink** [comment]
We are now using the `good-first-issue` tag. I think that resolves this issue.

**Comment by emmairwin** [comment]
Closing issue based on previous comment
