### ISSUE TITLE
Discussion on adding extra sections on the demographics

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-diversity-inclusion#34]
According to @serebrenik, we should discuss the following ideas: "I would also (1) separate sexual and romantic orientation and (2) add religion (or lack thereof) as a dimension."

Initial discussion at https://github.com/chaoss/wg-diversity-inclusion/pull/21

**Comment by aserebrenik** [comment]
For distinction between sexual and romantic/affective orientation see Lisa M. Diamond "[What Does Sexual Orientation Orient? A Biobehavioral Model Distinguishing Romantic Love and Sexual Desire](https://www.researchgate.net/profile/Lisa_Diamond4/publication/10949788_What_Does_Sexual_Orientation_Orient_A_Biobehavioral_Model_Distinguishing_Romantic_Love_and_Sexual_Desire/links/587ae03708ae4445c0630b9e.pdf)" in Psychological Review 2003, Vol. 110, No. 1, 173–192.

**Comment by aserebrenik** [comment]
ACM has published Draft 3 of their code of ethics. Section 1.4 explicitly lists demographic aspects that should be taken into consideration. Examples of the aspects included in their list and absent from ours are labor union membership and military status. See https://ethics.acm.org/2018-code-draft-3/

**Comment by emmairwin** [comment]
@serebrenik would love a PR for these additions to https://github.com/chaoss/wg-diversity-inclusion/blob/b473bf2813e6eb2c5cf38a52185e1289252505c8/demographic-data/README.md

And if you have a preferred standard for these, those would be greatly appreciated as additions to:  https://github.com/chaoss/wg-diversity-inclusion/tree/06a43c7504f7552df42f08a439715f2f49610d02/demographic-data

**Comment by germonprez** [comment]
closing as addressed with issue #312
