### ISSUE TITLE
Tools to evaluate PR Quality

### ISSUE THREAD

**Issue by akshitac8** [chaoss/wg-diversity-inclusion#57]
- [ ] State the tools that can be used to evaluate the PR quality.

**Comment by akshitac8** [comment]
Some of the tools to evaluate PR includes:
 - [ ] Travis 
 - [ ] pep8 speaks
 - [ ] review-bot
 - [ ] sentiment-bot
@emmairwin @GeorgLink What do you suggest?

**Comment by aserebrenik** [comment]
There are quite some academic studies relating features of the PR with likelihood of it to be merged or duration of the code review. If one is interested in shorter review periods or PRs that are more likely to be merged, one could look into this literature as well.

**Comment by akshitac8** [comment]
Oh, Thank you @aserebrenik 😃

**Comment by emmairwin** [comment]
@akshitac8 can we close this issue? Or you are still proposing?

**Comment by emmairwin** [comment]
Closing
