### ISSUE TITLE
Missing Information in Project Places (metric)

### ISSUE THREAD

**Issue by asarma** [chaoss/wg-diversity-inclusion#58]
Hello, I was reviewing our metrics on Project Places (https://github.com/chaoss/wg-diversity-inclusion/blob/master/goal_project_places.md) and I think we should include the following additional aspects in the document:
What do you think? Perhaps we can discuss this in our next call?

* Sample Objectives:
  * (Information Amount) Documentation provides information so that people gather as much information as they want, and no more than they want
  * (Learning by Doing) Documentation encourages hands-on learning, but doesn’t require it
  * (Learning by Process) Documentation provides not only details of every step, but also how these steps fit together in the process

* Sample Strategies:
  * Use the GenderMag Heuristics to evaluate the document’s gender-inclusivity. (http://gendermag.org/downloadables/GM-Heuristics-2018-0704.pdf )

* Sample Metrics: 
  * Gender-inclusivity:
TODO: what result will indicate good diversity and inclusion?
“Score” on the GenderMag Heuristics (count of how many supported out of 5)
“Score” on the “Sample Objective” list (count of how many supported out of the length of the list)

Thank you @dicortazar for helping me with this issue.

**Comment by GeorgLink** [comment]
​Thanks Anita.

**Comment by emmairwin** [comment]
@asarma with some reorg of the repo, I am not sure if this is happened, or is still relevant.  Can you please update?  Thanks

**Comment by Erioldoesdesign** [comment]
http://gendermag.org/downloadables/GM-Heuristics-2018-0704.pdf < does not exist anymore :(

**Comment by Nebrethar** [comment]
https://gendermag.org/Old_GM_Site/downloadables/GM-Heuristics-2018-0704.pdf < new link

**Comment by GeorgLink** [comment]
Closing until we revisit this metric.
