### ISSUE TITLE
Sandbox for issues and PRs

### ISSUE THREAD

**Issue by asarma** [chaoss/wg-diversity-inclusion#59]
Hello, would it make sense to have a sandbox where newbies can first raise issues/create pull requests within our group before making it visible to the entire world?

**Comment by GeorgLink** [comment]
I understand where you are coming from.

How would the mechanics work? Aren't all issues and pull requests public?
How would newbies get access if a repository was not public?
​

**Comment by GeorgLink** [comment]
@asarma is this issue still a concern? 
I'll close the issue for now, but please do re-open if this should be resolved.
