### ISSUE TITLE
Define 'Path to Maintainership' and 'List Maintainers'

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#6]
Per proposal in chaoss/governance#5 :

> The README.md of the repository contains a list of who is maintainer. Each CHAOSS repositry brings together different people and they document in the repository specific CONTRIBUTING.md how somone becomes a maintainer on their repository.

TODO:
- Specify 'path to maintainership' for this repo in CONTRIBUTING.md file
- List current maintainers in README.md file

**Comment by drashti4** [comment]
You mean to create different file for CONTRIBUTING.md. As I can see there are two maintainers You and dicortazar. Do you want any other name to add like mentor or anything. I would love make PR for this.

**Comment by GeorgLink** [comment]
Hi @drashti4 

Thank you for picking this up. For a template of what I was thinking of, take a look at the [chaoss/metrics repository](https://github.com/chaoss/metrics/)

While I contribute to the repository, I prefer to **not** be a maintainer.

Thanks again,
Georg

**Comment by emmairwin** [comment]
@GeorgLink is this still relevant?

**Comment by GeorgLink** [comment]
Yes, this appears to be relevant. 

I could not find documentation (README.md and CONTRIBUTING.md) on how to become a maintainer for the D&I repository.

**Comment by GeorgLink** [comment]
We have this information in our README.md now.
