### ISSUE TITLE
How to create a good goal-metric

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-diversity-inclusion#66]
@GeorgLink In the [focus area template](https://github.com/chaoss/wg-diversity-inclusion/blob/master/templates/focus_area.md), I want to link to an example/directions/criteria for how to write a good goal-metric.  Do you have something like that?

**Comment by GeorgLink** [comment]
I have not been keeping track of whether we were creating "good" goal-question-metric relationships. We might be trailblazers who set the standard for the CHAOSS project.

Below is not a definitive answer, but my thoughts on goal-question-metric formulation. I inform my musings through [Basili, Caldiera, and Rombach](http://www.cs.umd.edu/~mvz/handouts/gqm.pdf).

A good goal should detail: 
- Issue (e.g., Diversity and Inclusion)
- Object (e.g., Project and Community Places)
- Viewpoint (e.g., Community)
- Purpose (e.g., Understand)

**Goal:** Understand the diversity and inclusion of project and community places from the viewpoint of community members.

A **question** may address (with examples):
1. How can we characterize project and community places (i.e., the object) with respect to the understanding diversity and inclusion?
  - What project and community places are used by a community?
  - What do we know about the people at these places?
2. How can we characterize the attributes of project and community places (i.e., the object) with respect to diversity and inclusion?
  - What demographics are represented at the project and community places?
  - Has the composition of demographics changed over time?
3. How do we evaluate the characteristics of project and community places (i.e., the object) that are relevant to understanding diversity and inclusion?
  - Are we meeting our diversity and inclusion goals?
  - Is the diversity and inclusion improving?

On the Resource Pages, we would then provide qualitative and quantitative ways to answer the questions. These methods for answering are the **metrics**.

I'm CCing CHAOSS members who might have experience with formulating goal-question-metric relationships and can help us: @germonprez @sgoggins @dicortazar @klumb @jgbarah @BenLloydPearson

**Comment by emmairwin** [comment]
This is great , thank you.

**Comment by GeorgLink** [comment]
I mentioned this issue in the weekly meeting today. We may have other
CHAOSS members join us tomorrow to discuss with us how to write good
goal-question-metrics.

**Comment by emmairwin** [comment]
Closing based on:  https://github.com/chaoss/wg-evolution/issues/18
Please open new issue if needed.
