### ISSUE TITLE
Bechdel test metric

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#67]
Tobie Langel shared a [tweet](https://twitter.com/amandaksilver/status/1038043794984194048?s=21) on the mailing list about adopting the Bechdel Test to Open Source.

I had to look up Bechdel test and include here what I found:

> The Bechdel test (/ˈbɛkdəl/ BEK-dəl) is a method for evaluating the portrayal of women in fiction. It asks whether a work features at least two women who talk to each other about something other than a man. (From: https://en.wikipedia.org/wiki/Bechdel_test)

The tweet Tobie referred to states:

> The equivalent of the Bechdel test would be that there is a PR for an OSS project which gets reviewed, commented on, and accepted without having a man on the PR history.

I read this to require for a pull request (assuming GitHub):
- A woman creates the pull request
- A woman maintainer accepts and merges the pull request
- No man has commented on or reviewed the pull request

We could add a Bechdel metric that is the ratio of pull requests that pass the Bechdel test.

This might be a suitable D&I metric. 
(without worrying about how to implement the metric for now).

**Comment by tobie** [comment]
@amandasilver is the author of the original tweet.

**Comment by aserebrenik** [comment]
As opposed to books and movies where the characters are assigned to do something or say something by the book/movie creators, pull requests are usually open for participation of anybody and developers can decide themselves whether they contribute or not, i.e., when movie/book characters do not have agency, developers do. Yet another difference is that many pull requests are not being reviewed at all

**Comment by emmairwin** [comment]
Which focus area do you think this belongs in?

**Comment by vjanicki** [comment]
{Late to the Party}  There may be an misinterpretation here. I would say the Bechdel test for OSS would be that, during the lifetime of a PR,  2 or more women have participated in the discussion and activity around the PR. Ideally at at least 1 point in time, the women interact with each other.  This could be the creation, acceptance, commenting, reviewing or merging steps.  This does not preclude others participating and interacting during the PR's life.

**Comment by emmairwin** [comment]
I like this version.
How would we measure is always tbr question as gender is not always clear
or purposely hidden/anonymous.

**Comment by aserebrenik** [comment]
Moreover, whether the gender is identifiable or not might change in time. However, this problem is present in any kind of automatic gender analysis of repository data.

We can redefine this test to refer to non-men as opposed to women. This would also include both non-binary individuals and individuals that prefer not to disclose their gender.

**Comment by emmairwin** [comment]
Yes!

**Comment by emmairwin** [comment]
I think someone could take a first-go at this, without not a lot of experience and based on this thread.  (added good first issue, to get this un-stuck this)

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
