### ISSUE TITLE
Develop Research Page: Project Places - Issue Tracker

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#71]
This issue is for coordinating around developing the resource page for **Project Places - Issue Tracker**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1s0R-ira9guSQU6dVQVV3AOgs2o1VWgJ3kpBbi5WCfPI/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by emmairwin** [comment]
Thanks for creating this

**Comment by emmairwin** [comment]
Added good first issue, I think someone can take a first-go at this and get it moving based on other metric areas.

**Comment by mariamgui** [comment]
Thank you for adding the "good first issue" tag. I am really interested in working on this.

**Comment by germonprez** [comment]
Great. Thanks @mariamgui! I do recommend that you check out the new metrics template located here: 

https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md

(You don't need the disclaimer to the activity metrics page -- at the top). 

We updated this template between when the issue was opened and now.

**Comment by mariamgui** [comment]
Thank you for the link @germonprez

**Comment by germonprez** [comment]
Cool. The disclaimer was fixed (it is no longer there) so you can disregard that comment that I made in parentheses :)

**Comment by mariamgui** [comment]
Added a first draft for this metric, feel free to add any feedback or new ideas :)

**Comment by germonprez** [comment]
Closing as this has been released as

https://chaoss.community/metric-issue-label-inclusivity/
