### ISSUE TITLE
Develop Resource Page: Project Places - Communication Channels

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#72]
This issue is for coordinating around developing the resource page for **Project Places - Communication Channels**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1quMb1e2Hsm6hPf6G4vY6JtS3GUGv9vBZ7JBcuzuCiFs/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by bistaastha** [comment]
@GeorgLink Hi! I am working on this document.

**Comment by GeorgLink** [comment]
Awesome, please let me know if you have any questions or thoughts. We can discuss this metric and your work on the next CHAOSS D&I WG call.

**Comment by bistaastha** [comment]
> Awesome, please let me know if you have any questions or thoughts. We can discuss this metric and your work on the next CHAOSS D&I WG call.

@GeorgLink That would be amazing :grin:

**Comment by bistaastha** [comment]
The original link to Documentation in Description did not point to the intended file anymore. Turns out it is the same for other documents as well. I changed the link in this one, and it seems like now it points to the correct place. Can I go ahead and fix this for other resource pages as well?

**Comment by bistaastha** [comment]
Hi @GeorgLink ! Under the Sample Objectives section, I've added four ways in which this metric could be used. While writing Sample Strategies, I was wondering if Code of Conduct could be used as a foundation for how the community members should interact. But if so, how could that be quantitatively measured? Also, could existing metrics be used directly to define new ones?

**Comment by GeorgLink** [comment]
Hi @bistaastha, thanks for engaging with the metric definitions. 

The google docs are based on an old template we had for metrics and we never got around to updating them. With the latest release, we decided to use a [new template](https://github.com/chaoss/metrics/blob/master/activity-metrics/metric-template.md) and have headings that match. -- I updated the headings in the google doc.

Yes, it is okay to define a metric based on existing metrics. For example, [Issue Response Time](https://chaoss.community/metric-issue-response-time/) is built on [Time to First Response](https://chaoss.community/metric-time-to-first-response/)

I don't understand your question about Code of Conducts in this context. Can you please clarify?

**Comment by bistaastha** [comment]
@GeorgLink Since Code of Conduct also defines rules for communication in channels, I was thinking if the [metric for Code of Conduct](https://chaoss.community/metric-code-of-conduct) could be used here to measure how inclusive a channel is supposed to be. But what if there is a difference between what the document states and how welcoming the environment of the channel is? Is there a way to measure that?

**Comment by GeorgLink** [comment]
I have not looked into this. I don't know if this can work. Feel free to make suggestions if you have ideas.

**Comment by bistaastha** [comment]
Hi @GeorgLink . I have added my ideas in the document.
Please let me know how I can improve this more. Thanks!

**Comment by GeorgLink** [comment]
Thank you for adding your ideas.

I think you are on the right track with this idea. Surveying is an important tool.

For this or any metric to be ready for release, we need to have the mandatory elements filled in and enough information.

I think we need a better description of this metric and why it is important. 

In the implementation section, we need more details on how to collect data. Maybe we can model the Implementation section after the example in the [Sponsorship](https://chaoss.community/metric-sponsorship/) metric. Specifically, we could benefit from a set of questions to include in a survey and details for how to administer the survey in the context of this metric.

Is this something you want to work on?

Thanks,
Georg

PS: In the future, it would help me review your changes if you could use the [suggest](https://support.google.com/docs/answer/6033474?co=GENIE.Platform%3DDesktop&hl=en) mode in the document.

**Comment by bistaastha** [comment]
Thanks for your feedback!
> In the implementation section, we need more details on how to collect data. Maybe we can model the Implementation section after the example in the [Sponsorship](https://chaoss.community/metric-sponsorship/) metric. Specifically, we could benefit from a set of questions to include in a survey and details for how to administer the survey in the context of this metric.
> 
> Is this something you want to work on?

Yes, I would like to work on this. 

I didn't get the part about administering the survey. Can you please explain it more? I am assuming it is the same as the Data Collection Strategy.

> PS: In the future, it would help me review your changes if you could use the [suggest](https://support.google.com/docs/answer/6033474?co=GENIE.Platform%3DDesktop&hl=en) mode in the document.

I'll keep this in mind. :)

**Comment by GeorgLink** [comment]
> I didn't get the part about administering the survey. Can you please explain it more? I am assuming it is the same as the Data Collection Strategies.

Yes, it is in the Data Collection Strategies. It would be nice to have some pointers for people who want to implement this metric about how to get started. E.g., do they post a survey link in each communication channel? Are the survey questions asked in a community survey? Are there micro-survey "feedback stars" (I don't know what they are called -- that asks contributors during their engagement with a communication channel one specific question that takes very little time to answer.

**Comment by bistaastha** [comment]
> Are there micro-survey "feedback stars" (I don't know what they are called -- that asks contributors during their engagement with a communication channel one specific question that takes very little time to answer.

@GeorgLink I looked up these tiny surveys, turns out they are called star-rating surveys ([reference](https://www.questionpro.com/features/star-rating.html)).

This will help a lot. Thanks!

**Comment by GeorgLink** [comment]
I also had something like this in mind: https://library.gv.com/micro-surveys-a-faster-way-to-learn-about-your-users-9a5ad64e1af2

**Comment by bistaastha** [comment]
> I also had something like this in mind: https://library.gv.com/micro-surveys-a-faster-way-to-learn-about-your-users-9a5ad64e1af2

This is awesome!

I am wondering if something like this can be implemented if someone is leaving a channel?
For example if someone is leaving a mailing list, they can be asked why. I just came across a survey of this kind today morning.

**Comment by bistaastha** [comment]
Hi @GeorgLink . I have added some questions to Data Collection Strategies. :)

**Comment by germonprez** [comment]
I am closing the issue as it has been labeled as a metric idea. The idea is that we can capture all metric ideas (either new metrics or additions to existing metrics). We can then look at all Metric Ideas collectively.
