### ISSUE TITLE
Develop Resource Page: Governance - Foundation Staff Diversity

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#77]
This issue is for coordinating around developing the resource page for **Governance - Foundation Staff Diversity**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/101e0JlHwxXNXH8dfaiZTEWjgG-YshBESao75PWHJaZA/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by dicortazar** [comment]
I've left a couple of comments, but there was already some work done.

**Comment by GeorgLink** [comment]
@dicortazar is this complete and ready for review or do you have additional ideas you want to add first?

**Comment by dicortazar** [comment]
After reviewing the issue, I've realized that there's already a merged version of this. And this follows the required template: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus_areas/governance/foundation_staff_diversity.md.

We may want to close this issue.

**Comment by dicortazar** [comment]
Closing this ticket as this was already resolved. Thanks to all for your valuable comments and please feel free to re-open the ticket if there's anything missed.

**Comment by GeorgLink** [comment]
Thanks @dicortazar
