### ISSUE TITLE
Develop Resource Page: Governance - Board/Council Diversity

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#78]
This issue is for coordinating around developing the resource page for **Governance - Board/Council Diversity**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/13toY8vWR5OGwiuLKzI7cmhnjqc7H8L9u-iUyRmE9egg/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by dicortazar** [comment]
I've added a few comments on top of the existing document.

**Comment by aserebrenik** [comment]
One of the strategies to ensure representativeness is open election of the board members.

**Comment by dicortazar** [comment]
@aserebrenik , would you say that this is a good policy to be more inclusive? This might be helpful to be part of the qualitative set of metrics in the 'Sample Success Metrics' section.

**Comment by aserebrenik** [comment]
@dicortazar not necessarily so. One of the objectives is "A project member needs to know that someone in the board or council is representing their interest": elections can help with ensuring that the interests of (some of) the project participants are represented. However, as elections go, they do not necessarily further diversity/inclusion since the majority can easily elect the candidates representing them as opposed to those representing a minority.

**Comment by GeorgLink** [comment]
Thanks @aserebrenik and @dicortazar  --- I added a method for observing open elections and made a comment referencing this thread. Take a look and see if this is helpful.

**Comment by dicortazar** [comment]
After reviewing this ticket, I've realized that this was already merged.

The existing doc at https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus_areas/governance/board_council_diversity.md follows the required template.

We may want to close this ticket.

**Comment by dicortazar** [comment]
Closing this ticket as this was already resolved. Thanks to all for your valuable comments and please feel free to re-open the ticket if there's anything missed.

**Comment by GeorgLink** [comment]
Thanks @dicortazar
