### ISSUE TITLE
Develop Resource Page: Governance - Code of Conduct

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#79]
This issue is for coordinating around developing the resource page for **Governance - Code of Conduct**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1DGiBT3lUaIcNJBsDICsliJPNumOglzFPGJKnWiU3pD0/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by emmairwin** [comment]
I'll also take this one

**Comment by GeorgLink** [comment]
Thanks @emmairwin. 

Question: Mozilla’s Code of Conduct Assessment Tool appears to be a good resource to evaluate your own code of conduct and fix common issues. Is the next step to develop a check-list or another way to capture the degree of quality? Similar to CII Badge? --- Or is that besides the point?

**Comment by aserebrenik** [comment]
A couple of points:
* Tourani, Adams, Serebrenik Code of Conduct in Open Source Projects. 24th IEEE International Conference on Software Analysis, Evolution, and Reengineering, pp. 24-33, 2017 http://www.win.tue.nl/~aserebre/SANER2017.pdf
* Dobson Why Ethics Codes Don't Work Financial Analysts Journal Vol. 59, No. 6 (Nov. - Dec., 2003), pp. 29-34 https://www.jstor.org/stable/4480525?seq=1#page_scan_tab_contents
