### ISSUE TITLE
Develop Resource Page: Governance - Code of Conduct Enforcement

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#80]
This issue is for coordinating around developing the resource page for **Governance - Code of Conduct Enforcement**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1O__IONyNX8KRlkwSgmPIvOuzx8M01WUr2gZy2j3cF7w/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by emmairwin** [comment]
I'll take this one, as it's related to work I am already doing at Mozilla.
