### ISSUE TITLE
Develop Resource Page: Governance - Team/Module Ownership Diversity

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#81]
This issue is for coordinating around developing the resource page for **Governance - Team/Module Ownership Diversity**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1How8BisNtZs7_coUonDA_99arbcXEZzyaOlxLMrbDBw/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by dicortazar** [comment]
Just filled a first version of the document based on the existing skeleton and description.

**Comment by dicortazar** [comment]
After reviewing this issue, the document was already merged at https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus_areas/governance/team_module_ownership_diversity.md

I've checked that this follows the required template.

I think we can close this ticket.

**Comment by dicortazar** [comment]
Closing this ticket as this was already resolved. Thanks to all for your valuable comments and please feel free to re-open the ticket if there's anything missed.

**Comment by GeorgLink** [comment]
Thanks @dicortazar
