### ISSUE TITLE
Develop Resource Page: Governance - Path to Influence

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#82]
This issue is for coordinating around developing the resource page for **Governance - Path to Influence**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1g3zMQpBgieUzkJN8Zw9QBgyStDmjCiw5NQaaMoM7hF0/edit

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by GeorgLink** [comment]
I fixed the URL in the original issue message, which had led to the wrong document. -- My apologies.

@emmairwin good question. I think that the name "path to leadership" is easier to grasp. Influence sounds more broad but I don't think it helps us in any way and we should go for the low hanging fruits (i.e., leadership) first. --- Should we change the title of this or is there another page you are working on about "Path to Leadership"?

**Comment by emmairwin** [comment]
The thing is,    we have to be careful here about saying there is any one path to leadership, because that might skew to a certain ability, available time etc.   Maybe we park this one until we have done more work on inclusive leadership attributes first?

**Comment by GeorgLink** [comment]
I'm okay with postponing this for now. 

I agree that we should not champion any one way but rather try to capture whether a project has a "path to leadership".
