### ISSUE TITLE
Develop Resource Page: Event Diversity - Diversity Access Tickets

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#85]
This issue is for coordinating around developing the resource page for **Event Diversity - Diversity Access Tickets**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1Gs1xm_-ojc6Y32pYmtdbROnMa81ux_RiK8aeXU43QtE/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by geekygirldawn** [comment]
Someone did a lot of work on this one - Thank you! I added a few more things, so this is ready to review.
