### ISSUE TITLE
Develop Resource Page: Event Diversity - Code of Conduct at Event

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#86]
This issue is for coordinating around developing the resource page for **Event Diversity - Code of Conduct at Event**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1XKrsbVCPA5dqEfOnMVRyRcjqRNS05icKLojdgQawph0/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by emmairwin** [comment]
In #80 O often reference events.
If this were code architecture, I would 
Suggest that Code of Conduct for events   'Inherits' Code of Conduct, and then has specifics for events.

**Comment by geekygirldawn** [comment]
Agreed! My plan was to talk only about the event-specific bits of the code of conduct and the impact on event D&I. We can link to the other docs under governance that contain more CoC information.

**Comment by GeorgLink** [comment]
Good idea +1
