### ISSUE TITLE
Develop Resource Page: Event Diversity - Kid Friendliness

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#87]
This issue is for coordinating around developing the resource page for **Event Diversity - Kid Friendliness**.

The resource page lives in the following google document for easy editing, commenting, and revision:
https://docs.google.com/document/d/1jiylWjkLm04paBcflkNn0-yahvy958ShiUbrKrG20Zs/edit?usp=sharing

Once the page is in a decent shape, we will put a copy of it in the repository as a markdown file.

To work on this issue, feel free to leave a comment here and start editing the document. For questions, feedback requests, and other coordination tasks, please leave a comment here on the issue.

**Please edit the google document directly and add your ideas to it. We can help with cleaning it up later.**

**Comment by geekygirldawn** [comment]
This one was off to a good start, so I did a bit of minor cleanup and now it's ready for review.
